violentmonkey/violentmonkey

- src/options/style.css
This issue popped up in Russian translation of Violentmonkey, so screenshots are in Russian:
The problem arises from incorrectly used `line-height` to set the distance between options: `line-height` makes it look like the two-line options are in fact different options. `padding-top` and `padding-bottom` give the same distance between the menus, but keep default distance between lines of the same menu.
> Fix multi-line options in side menu of Dashboard

- src/_locales/ru/messages.yml
Completed Russian localization with context of each sentence in mind:
0. All items have a translation now;
1. Factually correct, e.g., prior translation had "Включить скрипты" ("Turn scripts on") instead of "Скрипты включены" ("Scripts are on");
2. Proper punctuation, e.g., check-boxes and tool tips terminate with punctuation, while buttons and headings do not;
3. Native Russian sentence structure and word choice instead of English-induced translation;
**In the translators list I included links to GitHub accounts.** See comment in the text box. This should not be a security issue, but I want to inform you about this.
> Complete Russian localization

- src/_locales/ru/messages.yml
Russian localization of recently added messages appearing in the search interface. Also, fix for the missing sync timestamp bug (caused by my earlier commit 'Complete Russian localization' 8f0b353341dfbf306310da002355a351c19e52cd).
> Russian localization for the search box

- src/injected/content/index.js
- src/injected/index.js
If we’re not going to run any scripts in the webpage, we may as well not inject the initializer either, right? This saves a bit of work, and avoids unnecessary Firefox CSP errors, on pages with no matched scripts.
> Skip injection of injected-web if there are no scripts to run

- src/popup/app.js
- src/popup/utils/index.js
- src/popup/views/app.vue
Hello @gera2ld.
- My first commit (abd734f23d320576d3a3c8f292aa0070d2295755) changes non‐working search URL like https://greasyfork.org/scripts?q=jasrac.or.jp into https://greasyfork.org/scripts/by-site/jasrac.or.jp
- Then my second commit (6f6029c2d74dea74604f66b932b9536d8f43d3cb) tries to remove the multiple domains sub menu as the search in Greasyfork is always by domain, never including sub‐domains (since JasonBarnabe/greasyfork#113)
I don’t know how to debug Chrome extensions so, please, if you have some time, test this and merge if you like it. :)
Or tell me what should be done if it does not work.
> Greasy fork find scripts /by-site/

- src/_locales/ru/messages.yml
I'm assuming here that "Value (serialized as JSON)" means you must supply a JSON text in the value field.
> ru locale update

- src/common/ui/style/style.css
[Add]
+ "Fira Code" is a great font for coding thanks to new font technologies.
+ Others are shipped with modern OSes. The list is borrowed from the CSS of Github website.
> More common monospace fonts for editor CodeMirror

- src/manifest.yml
Here's a simple fix for the warning below, which is seen in Firefox console when violentmonkey is installed:
`addons.webextension.{aecec67f-0d10-4fa7-b7c7-609a2db280cf} WARN Please specify whether you want browser_style or not in your browser_action options.`
Regards
> Fix 'browser_style' warning

- src/common/ui/style/style.css
So that we do not rely on unknown browser defaults and avoid a situation in which text has a similar color as the background (which has its color already defined in a stylesheet).
> Define default text colors in CSS

- src/_locales/en/messages.yml
When there are zero of something, you refer to it with the plural.
Also, I replaced the straight single quote with the actual apostrophe character (which is the same character as a closing curly single quote).
This is just a mockup made with the Inspector. I didn’t actually rebuild the extension.
> Fix grammar of labelNoScripts.message string

- src/common/browser.js
If a web page has `<html id="browser">` it'll create a global variable `browser` as per the [specification](https://html.spec.whatwg.org/multipage/window-object.html#named-access-on-the-window-object).
Violentmonkey needs to guard against it since browser.js also runs in a content script. This PR adds a check for the prototype just like [Mozilla's WebExtension polyfill](https://github.com/mozilla/webextension-polyfill/pull/153) does.
> guard against an implicit global variable for <html id="browser">

- src/popup/style.css
- src/popup/views/app.vue
With this PR customCSS can reorder/hide disabled scripts in popup by setting `flex` on `.submenu` and `order` or `display` on `.submenu .disabled`.
Ideally I would like to implement this as a user option in the dashboard but you seem to prefer the minimalistic built-in set of options, right?
> allow customCSS to reorder/hide disabled scripts in popup

- src/injected/content/index.js
- src/injected/web/index.js
Fixes #217 for real.
VM's `bridge` uses DOM messaging, which is synchronous, so we can return the element immediately.
`.then()` is still present on the returned value for compatibility with VM's 2017-2019 behavior.
> return the element immediately in GM_addStyle

- src/background/utils/script.js
- src/common/consts.js
- src/injected/web/index.js
- test/background/script.test.js
* `//` + single ASCII space is apparently hardcoded in almost every userscript-related app/site as noted in the discussion that ensued in #610 after the initial PR relaxed the parser
* we'll still allow whitespace **before** `//` like TM and greasyfork.org do in the hope that other entities reconsider as indentation sometimes is added by bundlers/postprocessors wrapping the code in IIFE and anyway indentation of a comment should not be enforced, especially in a language that's not indentation-based.
> reuse meta parser regexp and require a single space after //

- src/common/router.js
- src/options/views/app.vue
- src/options/views/tab-installed.vue
* Loading directly into the editor - when clicking the new/edit button in the popup
* Loading directly into the other tabs (settings, about)
* Also on manual reload of the options page via <kbd>F5</kbd> etc, for whatever reason.
* Slow page load in case there are many scripts (100, for example)
* Flicker of the temporarily shown header element when loading into the editor.
`v-if` is used to postpone rendering of the script list and the header.
Once eventually rendered, `v-if` is pinned in its enabled state to avoid re-rendering.
Basically it's like `{once: true}` in DOM messaging.
<details><summary>Repro:</summary>
1. click "settings" or "about" sub-page
2. click "Installed scripts"
3. click to edit a script
4. press the browser's history back button/key
5. press the browser's history …
> Faster initial loading of script editor and settings/about

- gulpfile.js
- package.json
- scripts/plaid.conf.js
- src/common/ui/style/index.js
- src/manifest.yml
- src/options/index.js
- src/popup/index.js
- yarn.lock
- Move scripts except `index.js` to `<head>` but keep `index.js` in `<body>` so that we don't have to check if `body` is ready everywhere. When `index.js` runs synchronously, first paint won't trigger because `<body>` is empty (except for `<script>`s).
```html
<head>
<script src="browser.js"></script>
<script src="common.js"></script>
</head>
<body>
<script src="index.js"></script>
</body>
```
- Load custom CSS from cache (`localStorage`) for the first time to avoid first paint with empty style.
When `DOMContentLoaded` is triggered after `index.js` runs, the custom style should have been attached to `<head>` and the main UI should have been rendered by Vue synchronously. So FOUC is avoided.
> fix: avoid FOUC

- src/common/router.js
- src/options/views/tab-installed.vue
This is a follow-up for #621: now that the state is not replaced we also need to observe `popstate` event on history back/forward.
Bug repro in the current master branch:
1. close all VM tabs
2. click '+' in the popup
3. click "Close" button in the editor
4. press the history back button/key in the browser
5. click "Close" button in the editor
Expected: the editor is closed and the script list is shown
Observed: nothing happens
> fix: update routes on 'popstate'

- src/background/utils/icon.js
Chrome extracts the icon data via Canvas API from each icon size specified and it wastes up to 40ms in our background page context (hence, blocking it for our code) each time a tab is opened that has a blacklisted or noninjectable state. The most frequent abuser is the default new tab page in Chrome.
This PR adds an explicit cache for imageData obtained via Canvas API.
> speed up setting icon data in Chrome

- src/background/index.js
- src/background/utils/cache.js
- src/background/utils/tester.js
- src/common/cache.js
- test/mock/polyfill.js
* `getScriptsByURL` before: ~90ms every time
* `getScriptsByURL` after: ~40ms first run, 2-20ms subsequent runs
1. only one `setTimeout` call per event loop cycle is used now in most cases, could be more if cacing items with progressively diminishing `lifetime` parameter, but we don't do that in bulk.
DOM timers are relatively expensive: ~50ms out of ~90ms was wasted on set/clearTimeout when there are many matches/globs (e.g. Handy Image userscript), and lots of cache items are generated by tester.js
2. `getScriptsByURL` is pre-calculated in webRequest.onHeadersReceived for main_frame/sub_frame and http/https URLs so when the content script sends GetInjected we already have the data.
3. All background cache lifetime was extended to 5 minutes.
Now userscripts run after ~20ms since the real …
> speedup: script injection

- src/popup/style.css
- src/popup/views/app.vue
Fixes #591.
Implementation notes:
* since only a small amount of scripts is shown I didn't use a cache for the icons
* all text was aligned to match "Violentmonkey" so the added padding on the left doesn't look weird
* `menu-group` and `menu-find` classes were added to target these non-uniform unique entries, which will be also helpful for customCSS (for example I've used a different color and font style).
> feature: show icons in the popup

- .babelrc.js
- package.json
- src/injected/content/clipboard.js
- src/injected/content/index.js
- src/injected/content/notifications.js
- src/injected/content/requests.js
- src/injected/content/tabs.js
- src/injected/content/util.js
- src/injected/index.js
- src/injected/utils/helpers.js
- src/injected/utils/index.js
- src/injected/web/download.js
- src/injected/web/index.js
- src/injected/web/requests.js
- test/mock/polyfill.js
Averaged numbers on www.google.com and nine scripts of various complexity/size.  
Six were running on `start`, two on `end`, and one on `idle`.
run-at | start | end | idle | total
---------|------|-----|------|---
Before, ms | 34 | 17 | 18 | 69
After, ms | 23 | 12 | 16 | 51
speedup %  | 33% | 30% | 10% | 25%
The most important improvement is `document-start` because it's the one that delays the page UI.
Measured using the simpler `JavaScript Profiler` in Chrome's devtools as it applies less overhead. Note that now document-start block in the flamechart is single (contiguous), but previously it consisted of two blocks due to `bridge.ready` which is now removed (see notes below).
* each `document-idle` script runs in its own setTimeout to prevent long pauses due to a lot of scripts running …
> speed up sandbox initialization up to ~33%

- src/background/index.js
- src/background/utils/options.js
- src/background/utils/script.js
- src/background/utils/template-hook.js
- src/common/ui/setting-text.vue
- src/common/ui/style/style.css
- src/popup/views/app.vue
* Adds a new automatically calculated boolean flag in `options` that's truthy if the default script template was edited. When it's falsy an update of Violentmonkey can also update the default template automatically without overwriting user's customized value.
* Aligns the `@grant` values for better readability
* Adds a few common keys: `@version`, `@author`, `@description`
> improvement: auto-updatable default script template

- src/background/utils/template-hook.js
Follow-up to #633: after the last refactor it lost its main intended feature, now restored in this PR.
> fix: actually update the default template when not edited

- src/popup/style.css
- src/popup/views/app.vue
Visual changes:
* script icon is increased from 17px to 18px
* find icon is increased from 14px to 16px
* script names got shorter by ~1px
* `Violentmonkey` title is centered vertically to match the buttons and uses the global font size
* failure reason left margin is fixed (it wasn't properly updated in the icons PR)
Before | After
-|-
Implementation notes:
* `postcss-custom-properties` plugin was hacked into postcss options directly as I couldn't find any other way due to my ignorance
* `px` are used for all the calculations so postcss-calc can resolve them at compile-time
> ui-cosmetics: use variables to align things in popup reliably

- src/background/utils/requests.js
Adds all [forbidden HTTP header names](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name).
> fix: add all forbidden header names

- src/background/utils/icon.js
Switches to using `isChrome`.
I've used `chrome.app` detection initially but `navigator.userAgent` is just as reliable inside an extension page, also `chrome.app` may go away in the future (https://crbug.com/768493).
> fix: reuse isChrome

- src/common/options.js
- src/common/ui/setting-text.vue
- src/options/utils/hotkeys.js
- src/options/views/app.vue
- src/options/views/script-item.vue
- src/options/views/tab-installed.vue
* Huge speedup of search filtering. Currently filtering re-renders each element (especially gruesome when the search text is backspaced so the elements previously filtered out need to be shown) which takes up to 400ms on a measly list of 100 items. This PR switches the implementation to `v-show` and uses an additional property in `$cache` so the time spent in Vue is just a few milliseconds, plus the time for the browser to do layout/paint which hasn't changed.
* Reduced the time in debouncedUpdate to 100ms as it's fast now
* Fixed a dead spot after `options.set` is called until `updateOptions` receives the new options.
* Disabled spellchecker in text areas in settings to prevent freezing of UI when customCSS is more than a hundred of lines
* Added autofocus of the search input on typing a …
> Speed up search in the script list

- src/background/utils/icon.js
- src/background/utils/requests.js
`pendingUrl` was added in Chrome 79, present while the tab connects to the newly navigated URL, https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/5zu_PT0arls
> fix: support Chrome's Tab.pendingUrl

- src/_locales/en/messages.yml
- src/background/utils/options.js
- src/common/options-defaults.js
- src/common/ui/code.vue
- src/common/ui/setting-text.vue
- src/common/ui/style/style.css
- src/options/utils/index.js
- src/options/views/edit/index.vue
- src/options/views/edit/keyboard.vue
- src/options/views/tab-settings/index.vue
- src/options/views/tab-settings/vm-editor.vue
The built-in editor can be much more convenient for quick edits if we enable a few trivial options in CodeMirror.
Fixes #242.
Fixes #596.
* the CodeMirror's `sublime` key map is a very small addon that makes the editor not a total PITA to use.
* user-customizable editor options JSON to accommodate for some weird setups like indentWithTabs etc.
* `?` sub-tab with the active key map cheat sheet:
Trivial UX changes:
* <kbd>Esc</kbd> closes the sub-tab first (Settings, Values, ?)
* <kbd>F1</kbd> shows the hotkeys tab
* CodeMirror is focused when switching back from other tabs so it's possible to press F1 (view the hotkeys), then Esc, then just keep editing without using the mouse.
> Trivial editor improvements

- src/options/style.css
Fixes this UI glitch:
1. open options.html not in the editor mode
Expected: the left panel doesn't shift when the logo image loads
Observed: sometimes (randomly) it shifts
This is totally unpredictable and rare but when it happens it's really noticeable.
To force the glitch you can simply reload the page repeatedly.
> fix: avoid layout shift when logo loads

- src/options/utils/throttled-render.js
Fixes this bug introduced by #623:
1. click `+` in the popup to create a new script
2. click `close` in the editor
Expected: script list is fully rendered
Observed: script list has only names/icons
Also happens after reloading the options.html page when the current sub-tab is not the script list.
P.S. added another check against batchSize being 0, the check was lost during some refactor of #623.
> fix: render the script list when it's not the first nav

- src/options/utils/hotkeys.js
- src/options/views/app.vue
Follow-up to #640.
Fixes the missed case of clean `options.html` URL with no routes.
> fix: enable hotkeys listener on page load

- src/common/index.js
- src/common/options.js
- src/injected/content/index.js
- src/options/index.js
The active page and its [content] scripts load before the extension's persistent background script when Chrome starts with a URL via command line or when configured to restore the session, https://crbug.com/314686
> fix: retry bg connection on startup in options.html

- src/popup/style.css
- src/popup/views/app.vue
Fixes a bug introduced by #635: when `src` is an empty string, Chrome repeatedly requests the invalid URL, stressing the CPU.
> fix: don't re-request missing script icons in popup

- scripts/plaid.conf.js
It's been bugging me for a while that `CodeMirror`, `tldjs`, `Vue` are loaded, parsed, compiled, and... are never used in some pages. This PR extracts them into separate files. Performance-wise I see no differences, but splitting should be better for memory consumption. Also, although Chrome doesn't seem to apply its parallelized loader/compiler to extension pages now, but it may change in the future, same for Firefox.
> chore: extract big vendor chunks

- src/injected/web/gm-api.js
- src/injected/web/gm-values.js
Follow-up to #636: the listener should be called after the local store is updated. This is also how it works in TM.
The mistake was caused by my initial async notification implementation, which I abandoned as it didn't match TM and it was overly complex as well as unnecessary: the userscript authors can debounce and accumulate changes if they need to.
> fix: notify ValueChange listener after updating the store

- src/injected/web/gm-api.js
- src/injected/web/gm-wrapper.js
Fixes #283.
GM4 uses `const GM=....` so userscripts can't redefine it, but our `GM` variable can be redefined. Not sure why we should protect it. The fact that GM4 uses `const` wasn't a security measure, it's just a trivial implementation detail, moreover the **contents** of `GM` object is not protected in GM4, while it is protected in VM so `GM.info = 1` will be ignored unlike in GM4.
> feat: add GreaseMonkey4 GM.* aliases

- src/_locales/en/messages.yml
- src/common/ui/code.vue
- src/options/views/edit/keyboard.vue
- src/options/views/tab-settings/vm-editor.vue
* toggle comments via <kbd>Ctrl</kbd><kbd>/</kbd>
* make /* block comment */ via <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>/</kbd>
* fix: <kbd>Tab</kbd> was incorrectly inserting a tab character when nothing is selected after #643
* fix: don't show missing CM commands in hotkeys tab
* a button to toggle display of current CodeMirror options in editor settings
> Editor tweaks

- src/options/utils/throttled-render.js
This is the same missed case like #654. Makes the first opening of the script list seem faster. In numbers it's ~300ms now vs ~400ms before.
> fix: also throttle script list rendering on first nav

- src/background/utils/requests.js
- src/common/browser.js
- src/common/ua.js
* when a valid .user.js is opened in a new tab (by drag'n'dropping or explicitly opening the URL in a new tab), it'll be autoclosed when the confirmation tab is shown.
* the confirmation tab will open next to the source tab and keep track of the opener tab id so on closing of the confirmation tab the opener tab will be focused.
> .user.js install tab tweaks

- src/popup/views/app.vue
Currently we have to be very accurate when clicking the edit overlay button in order not to toggle the script accidentally due to missing the target by a few pixels. This PR makes it so that a `Right-click`, `Ctrl-click`, or `Middle-click` on a script name opens it in the editor. Same as in Tampermonkey or Stylus extension.
> feat: edit on right-click or Ctrl-click at script name in popup

- src/background/utils/requests.js
- src/background/utils/tabs.js
* Adds a missing check for isAndroid in the new code for confirmInstall
* Adds a missing check for FF version >= 57 in the old code for tabOpen
> fix: ensure openerTabId is used only when supported

- src/injected/web/gm-wrapper.js
> fix: allow properties on window to be redefined

- src/options/views/tab-settings/vm-export.vue
- src/options/views/tab-settings/vm-import.vue
* Saves script's lastModified and lastUpdated on export and restores them on import
* Sets file date inside zip accordingly
This implements the missing aspect of a conventional backup behavior - seamless/nondestructive operation. Now we can export/import any time without losing the ability to see real last modification/update timestamps and use them to sort the list.
> feat: save&read script update/mod datetime in backup zip

- src/background/index.js
**TL;DR:**
Fixes the not-so-rare case when `GetInjected` message arrives while `getScriptsByURL` is still waiting for browser.storage. 
**More info:**
It usually happens when navigating a URL for which there is no data cached by `testScript` recently. With my 100 scripts (half enabled) it takes 40ms for getScriptsByURL to match all scripts. During this time `GetInjected` arrives and sees nothing in the preinject cache so it runs a second `getScriptsByURL`, which is faster of course since all the matching cache was primed by the first run, but still it's 5-10ms (plus another 5-10ms waiting for browser.storage), which is a non-negligible time span as we're trying to deliver the scripts to the web page tab ASAP.
> fix: wait for active getScriptsByURL and use its result

- src/_locales/en/messages.yml
- src/background/index.js
- src/background/utils/icon.js
- src/common/index.js
- src/common/options-defaults.js
- src/common/options.js
- src/confirm/views/app.vue
- src/injected/content/clipboard.js
- src/injected/content/index.js
- src/injected/content/inject.js
- src/injected/content/notifications.js
- src/injected/content/requests.js
- src/injected/content/tabs.js
- src/injected/index.js
- src/injected/utils/index.js
- src/options/index.js
- src/options/views/edit/index.vue
- src/options/views/edit/values.vue
- src/options/views/script-item.vue
- src/options/views/tab-installed.vue
- src/options/views/tab-settings/vm-blacklist.vue
- src/options/views/tab-settings/vm-export.vue
- src/options/views/tab-settings/vm-import.vue
- src/options/views/tab-settings/vm-sync.vue
- src/popup/index.js
- src/popup/style.css
- src/popup/utils/index.js
- src/popup/views/app.vue
Fixes #664.
Adds `sendCmd(cmd, data)` method, which I can split off into a separate PR (and also convert to async/await) if you wish. 
Test links (also try blacklisting the main page URL):
* https://jsfiddle.net/chrisvfritz/50wL7mdz/
* https://chrome.google.com/webstore/detail/ocfjjjjhkpapocigimmppepjgfdecjkb
BTW what do you think about enabling Stage-3 [nullish-coalescing-operator](https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator) and then replacing most of `objectGet(obj, 'foo.bar', def)` with `obj.foo?.bar ?? def` ? The only caveat I see is that technically it's not the same behavior as objectGet, which checks `key in res`, so if VM stores `null` or `undefined` somewhere in its data objects, we'd better not use `??` at all in order to avoid possible …
> Show unique iframe scripts in popup

- src/background/utils/requests.js
- src/common/util.js
- src/injected/web/requests.js
It's convenient, the vanilla XHR has it, Tampermonkey has it, the implementation is simple.
Collateral changes:
* simplified arraybuffer/blob response handling
* no progressive string concatenation in buffer2string
* on-demand decoding of GM_xmlhttpRequest 'response'
> feat: allow responseType 'document' in GM_xmlhttpRequest

- src/_locales/en/messages.yml
- src/common/options-defaults.js
- src/options/views/tab-settings/index.vue
- src/popup/views/app.vue
Since I've never needed to care about the execution order in all the years I've been using userscripts I have a reason to believe the same applies to most users, at least to a lot of them, so this PR adds several options to display the scripts in the popup in a more human-friendly way, mostly useful when there are many scripts installed.
* alphabetical order (default: execution)
* enabled scripts first (default: false)
* disabled scripts hidden (default: false)
The default state preserves the historical behavior.
**Collateral change:**
* Removed the implicit space between the checkbox and its text in settings + aligned them vertically against each other.
> Sort & filtering in popup

- src/background/sync/webdav.js
Nextcloud WebDAV doesn't return the DAV:displayname prop. Using filename from DAV:href.
Tested using Nextcloud 16.0.5.
> Fix WebDAV sync to Nextcloud

- src/injected/content/clipboard.js
Fixes #685.
In addition to a bug in my implementation (preventDefault and stopImmediatePropagation should be picked from Event.prototype) there's apparently a bug/quirk in Firefox which prevents the entire setClipboard+onCopy hack from working when ::safe calls are used. ~I guess Firefox somehow changes the initial methods or it uses a Proxy internally on `document` specifically. It's a mystery for me because in other parts of the content script the similar safe calls work correctly with `window::addEventListener` and `document::getReadyState`.~ 
Turns out there was another bug in my code + old versions of FF define execCommand in document.__proto__ not in Document.prototype...
> fix: GM_setClipboard in FF

- src/injected/web/gm-api.js
- src/injected/web/index.js
- src/injected/web/load-scripts.js
* Fixes #692: shows uncaught errors for `@inject-into content` mode
* Restores script name in GM_log (shown as the source at the right side of devtools console) lost in 8f43c1e65a2809f6c8a5a681ed2d91eb247a12f7
> display errors in content script mode

- .eslintrc.js
- src/common/browser.js
- src/common/consts.js
- src/common/handlers.js
- src/common/index.js
- src/injected/content/bridge.js
- src/injected/content/inject.js
- src/injected/web/gm-wrapper.js
- src/injected/web/index.js
Currently userscripts injected in content mode can freely use `unsafeWindow.browser` and `chrome` or `unsafeWindow.chrome` to abuse the internal messaging/storage of Violentmonkey. This PR makes it impossible by saving the originals into local variables and setting the originals to `undefined`.
> fix: really hide chrome.* and browser.* from userjs in content mode

- .babelrc.js
- .browserslistrc
- scripts/plaid.conf.js
- scripts/webpack.conf.js
* added a missing DefinePlugin for injected-web.js to strip 1.6kB of 'process' dep
* converted functions to arrows in terser in injected*.js
* using array destructuring in params to strip 0.5kB of babel's _iterableToArrayLimit added for `const [foo] = bar` assignments
22->19kB `–17%` injected-web.js
17->11kB `–35%` injected.js
~I don't know how to apply DefinePlugin to the entire project to remove the `process` dep from common.js as well.~
> chore: shrink injected* by 20%

- src/background/sync/base.js
- src/background/utils/commands.js
- src/background/utils/tabs.js
- src/common/index.js
- src/confirm/views/app.vue
- src/injected/content/index.js
- src/options/views/tab-installed.vue
- src/popup/index.js
- src/popup/views/app.vue
Tabs opened from popup will use `tabOpen()` so they are opened next to the source and have openerTabId (on closing of such a tab the source tab will be focused).
Collateral refactor: deduplicate getActiveTab() and makePause()
> feat: open tabs from popup using tabOpen()

- src/_locales/cs/messages.yml
- src/_locales/de/messages.yml
- src/_locales/el/messages.yml
- src/_locales/en/messages.yml
- src/_locales/es/messages.yml
- src/_locales/fi/messages.yml
- src/_locales/fr/messages.yml
- src/_locales/hr/messages.yml
- src/_locales/id/messages.yml
- src/_locales/it/messages.yml
- src/_locales/ja/messages.yml
- src/_locales/ko/messages.yml
- src/_locales/pl/messages.yml
- src/_locales/pt_BR/messages.yml
- src/_locales/pt_PT/messages.yml
- src/_locales/ro/messages.yml
- src/_locales/ru/messages.yml
- src/_locales/sk/messages.yml
- src/_locales/sr/messages.yml
- src/_locales/tr/messages.yml
- src/_locales/uk/messages.yml
- src/_locales/vi/messages.yml
- src/_locales/zh_CN/messages.yml
- src/_locales/zh_TW/messages.yml
- src/options/views/edit/index.vue
* show controls, name, and nav in the same row
* shorten the how-to hint and make it translatable
* chore: remove the unused warnScriptLongLines/tooLarge code
Fixes #526.
Narrow width example:
> ui: reduce header in the editor

- src/common/ui/code.vue
For some weird reason the old regexp was failing on a super big script like YoutubeCenter. The new one here is simpler/faster.
> fix: simplify regex for overly long lines

- .eslintrc.js
- package.json
- src/common/consts.js
- src/common/options-defaults.js
- src/common/ui/setting-text.vue
- src/common/ui/style/style.css
- src/injected/content/inject.js
- src/injected/web/gm-wrapper.js
- src/injected/web/load-scripts.js
- src/options/views/edit/index.vue
- src/options/views/tab-settings/index.vue
- src/options/views/tab-settings/vm-blacklist.vue
- yarn.lock
Implement Firefox-only injection-mode `wrap`.
close #702 .
- Add injection mode `wrap` in Firefox. In `wrap` mode `unsafeWindow` will be `window` from the page context even if the script is running in content page.
- Change `@inject-into` into a whitespace separated mode list, which equals to `auto` or consists of `page`, `content`, `wrap`. VM will try to find the first available injection mode from the list. The following definitions are identical:
```js
// @inject-into auto
// @inject-into page wrap content
```
- Change settings of default injection mode from a select box into an input box, so that users can define the desired mode list more easily. Since an input box seems confusing to normal users, I moved it to advanced settings.
> Implement Firefox-only injection-mode `wrap`

- src/options/utils/dragging.css
- src/options/utils/dragging.js
- src/options/views/script-item.vue
Fixes #720.
Collateral changes:
+ highlight the dragged element's background, otherwise it's kinda easy to confuse which one is under a finger
+ various speedups noticeable on slow mobile devices
> fix: drag'n'drop on touch devices

- src/common/consts.js
- src/injected/content/inject.js
- src/injected/web/gm-wrapper.js
In `wrap` mode, `unsafeWindow` is set to `wrappedJSObject`.
Consequently, we get "Permission denied to access object" error
when trying to access objects in `wrappedJSObject` from `content` script.
This is by design in Firefox and seems unable to be fixed by us, so we
remove `wrap` mode here.
close #733
> fix: remove `wrap` mode in Firefox

- src/common/ui/code.vue
- src/common/ui/style/style.css
- src/common/ui/toggle-button.vue
- src/options/style.css
- src/options/utils/dragging.css
- src/options/views/edit/index.vue
- src/options/views/edit/values.vue
- src/options/views/script-item.vue
- src/options/views/tab-about.vue
- src/options/views/tab-installed.vue
- src/options/views/tab-settings/vm-editor.vue
- src/popup/style.css
A simple built-in dark theme that activates on [prefers-color-scheme: dark](https://caniuse.com/#search=prefers-color-scheme) automatically in new browsers when the OS and the browser are using the dark mode.
Notes:
* almost all colors are mapped to a simple palette of 16 colors ranging from `#000` to `#fff` in the default theme and from `#222222` to `#b8b8b8` in the dark theme
* a few colors were approximated with the closest one from the palette
* a disabled `<button>` was simplified by using opacity instead of three separate colors
P.S.
Ideally I'd like to extract all media queries in a separate dark.css and load it conditionally:
```html
<link href="dark.css" rel="stylesheet" media="(prefers-color-scheme: dark)"/>
```
so that I could add a user option to force the dark theme in older …
> feat: automatic dark theme in supported browsers/OS

- src/background/index.js
- src/background/utils/requests.js
- src/common/browser.js
- src/injected/web/requests.js
- src/manifest.yml
Fixes #606.
Per [GM4 behavior](https://github.com/greasemonkey/greasemonkey/blob/80b179bc5ecb9af12c771c998aed4e81b9ca0d74/src/bg/on-user-script-xhr.js#L125-L149) cookies will be sent in these cases:
* when `withCredentials: true`
* when gmxhr URL origin === tab URL origin
> feat: send gmxhr cookies explicitly (needed in FF)

- src/background/index.js
- src/common/ua.js
- src/injected/content/clipboard.js
- src/injected/content/inject.js
Makes UA detection work in FF52 which doesn't define `BrowserInfo` in the runtime object.
> fix: use isFirefox from extension context in injected/*

- src/background/index.js
- src/background/utils/icon.js
- src/background/utils/requests.js
- src/background/utils/tabs.js
- src/common/browser.js
- src/common/ua.js
- src/injected/content/inject.js
- src/injected/web/gm-wrapper.js
- src/injected/web/index.js
- src/options/utils/dragging.js
- src/options/views/tab-settings/vm-export.vue
Implements and fixes #763.
```js
console.log(GM_info);
```
```js
const isChrome = GM_info.platform
? GM_info.platform.browserName === 'chrome'
: /Chrome/i.test(navigator.userAgent);
```
> feat: expose browser/platform info in GM_info.platform

- src/common/storage.js
Broken in 893f1400, looks like I've managed to copypaste it the wrong way somehow.
> fix: erroneous braces in storage.cache.fetch

- src/injected/web/requests.js
This fixes GM_xmlHttpRequest.abort, it didn't work previously.
> Fix req.abort

- src/injected/content/index.js
- src/injected/web/gm-api.js
GM_unregisterMenuCommand didn't work previously, and GM_registerMenuCommand didn't work as Scriptish and TM worked (i.e. returning the menu ID).
> Fix GM_(un)registerMenuCommand

- src/injected/web/gm-wrapper.js
Fixes #765.
FF doesn't expose wrappedJSObject via Object.getOwnPropertyNames so this PR explicitly adds it.
> fix: explicitly add window.wrappedJSObject to the wrapper

- src/background/index.js
- src/background/utils/requests.js
- src/injected/content/requests.js
- src/injected/web/gm-api.js
- src/injected/web/requests.js
Fixes #777.
1. extension messaging has a 128MB limit on the payload size so buffer2string is limited to 64MB as it uses just one byte out of two. **Solution:** URL.createObjectURL is used to transfer a small blob URL, then its contents is retrieved explicitly using XHR in the content script. This workaround is enabled only when `responseType` parameter is `blob` or `arraybuffer`. Ideally we could do that for all response types but I think we shouldn't do it unless someone reports at least one sensible use case.
2. extension API doesn't seem to guarantee the order of messages is preserved so now `xhrCallbackWrapper` will wait for the previous message before sending the next one.
> fix: handle gmxhr blob/arraybuffer > 64MB

- src/injected/web/requests.js
Follow-up for #778: it unnecessarily could fetch the blob many times. I've introduced this bug while reducing nestedness of ifs.
> fix: fetch blob only once

- src/background/utils/tester.js
It was incorrect since my initial implementation in fcbd53ad7d3ab14bb18de6970fd0273d49263dff.
> fix: blCacheSize calc should use key length

- src/background/utils/update.js
- src/options/views/script-item.vue
Fixes #67.
Border, icon, message are reddened:
And a standard DOM tooltip with the URL is shown on hover:
The feature itself was trivial so to make things more interesting I've refactored update.js to use async/await. Hopefully the new code has a more obvious execution flow.
> feat: recolor script-item on update error + refactor update.js

- src/background/index.js
- src/background/plugin/index.js
- src/background/sync/base.js
- src/background/sync/index.js
- src/background/utils/cache.js
- src/background/utils/clipboard.js
- src/background/utils/commands.js
- src/background/utils/db.js
- src/background/utils/hotkeys.js
- src/background/utils/icon.js
- src/background/utils/index.js
- src/background/utils/init.js
- src/background/utils/message.js
- src/background/utils/notifications.js
- src/background/utils/options.js
- src/background/utils/patch-db.js
- src/background/utils/requests.js
- src/background/utils/script.js
- src/background/utils/tabs.js
- src/background/utils/template-hook.js
- src/background/utils/tester.js
- src/background/utils/update.js
- src/background/utils/values.js
- src/common/consts.js
- src/common/index.js
- src/common/object.js
- src/popup/index.js
- src/popup/views/app.vue
Despite the big amount of moved stuff the underlying changes are simple: 
* converted functions to `async` using an automatic converter + some manual tweaks
* optional chaining and other new stuff like object spread
* `commands` registration is split per module so the main index.js is now small
* `sendTabCmd` is used for tabs/frames 
* `sendCmd` ignores errors when called in the background script
> refactor bg

- src/injected/content/bridge.js
- src/injected/content/index.js
- src/injected/content/inject.js
- src/injected/content/notifications.js
- src/injected/content/requests.js
- src/injected/content/tabs.js
- src/injected/index.js
- src/injected/utils/index.js
- src/injected/web/bridge.js
- src/injected/web/gm-api.js
- src/injected/web/gm-values.js
- src/injected/web/gm-wrapper.js
- src/injected/web/index.js
- src/injected/web/load-scripts.js
- src/injected/web/notifications.js
- src/injected/web/requests.js
- src/injected/web/tabs.js
Trivial refactor of injected/*
* separate params of bridge.post for consistency with `sendCmd`
* optional chaining
* async/await
* simplified UpdatedValues a bit
> refactor: separate params of bridge.post + more ES20xx

- .eslintrc.js
- src/common/browser.js
* don't process code needlessly in Firefox
* add a debugging .catch() only in debug builds
* use optional chaining
* use binding::call
* trivial code cosmetics like extracting wrapMessageListener to make the main API definition object smaller and more readable
* simplify eslint.rc
> refactor: tweak browser.js

- src/_locales/en/messages.yml
- src/common/hook-setting.js
- src/common/options-defaults.js
- src/common/options.js
- src/common/ui/setting-check.vue
- src/common/ui/setting-text.vue
- src/options/views/tab-installed.vue
- src/options/views/tab-settings/index.vue
Default mode is `name`, which restores the old behavior (before code search was enabled by default). The reason is that searching code by default may often produce irrelevant results due to matching a common JS term or a common metablock value.
I've used a dropdown selector instead of a simple `[x] in code` because we may want to add other modes in the future like maybe `values` or individual meta keys.
Collateral:
* common/options getOption() now uses options-defaults.js to get the fallback value instead of the second parameter which wasn't used anywhere (AFAICT it was added just in case, only because options-defaults.js wasn't exposed).
* a tooltip with regexp search hint is added to the search icon
* refactor: deduplicate/simplify hookSetting() usage so it automatically calls …
> feat: add scope name|code|all to dashboard search filter

- src/background/index.js
- src/background/sync/base.js
- src/background/utils/db.js
- src/background/utils/options.js
- src/background/utils/requests.js
- src/background/utils/script.js
- src/background/utils/values.js
- src/common/browser.js
- src/common/hook-setting.js
- src/common/index.js
- src/common/object.js
- src/common/options.js
- src/common/util.js
- src/injected/web/gm-api.js
- src/injected/web/gm-values.js
- src/options/index.js
- src/options/views/edit/help.vue
- src/options/views/tab-settings/vm-import.vue
- src/popup/index.js
Main change:
* `openers` now also stores frameId which is used to skip sending the updates to the initiator (the script that introduced this particular change)
* each tab's frame gets its own message with updates only for the scripts running in that frame
Collateral changes:
* `tabScripts` is removed because it's enough to enumerate the entire `openers` - there will be just a few script ids (or maybe a few dozen for super hardcore users)
* objectSet() can treat the final value as an array if the last key is also an array, for example `objectSet(obj, ['foo', ['bar']], value)` will set `obj.foo.bar = []` if needed and then do `obj.foo.bar.push(value)`.
* The second commit adds ::forEachEntry, ::forEachValue, ::mapEntry so despite it being trivial you still may find it easier to review the …
> rework/simplify GMxxxValueChanged handling

- src/background/utils/db.js
- src/background/utils/values.js
- src/common/object.js
- src/options/views/tab-installed.vue
Follow-up to #806.
It was remembering the entire change history and thus mistakenly aggressive in avoiding to send the updates, but what we really need is only to check for the last set value in each frame because this value is what's being sent to all other tabs/frames during the current broadcast call.
Added ::forEachKey() for consistency but there are only 3 calls so maybe there was no need? On the other hand, the concise form looks so good.
Reverted objectSet's support of an array because `openers` can use an object for frameId just fine.
> fix: only skip sending the last known value

- src/common/browser.js
- src/common/hook-setting.js
- src/common/options.js
- src/common/ui/setting-check.vue
- src/common/ui/setting-text.vue
- src/options/views/tab-installed.vue
- src/options/views/tab-settings/index.vue
The benefit of this approach is that it's easier to see usages of a symbol, particularly via "Find usages" command in IDE.
Added: browser.js prefetches the options while an extension page loads to drastically reduce the probability of options being not ready. It reduces the UI flicker, for example [re]loading `options/index.html#settings` now shows the real settings in the first paint of the page.
> refactor: restore simple hookSetting, prefetch options

- src/background/utils/options.js
- src/background/utils/script.js
- src/common/object.js
- src/popup/index.js
For consistency with forEachEntry and in order not to deviate from standard Object.keys+map.
> refactor: invoke mapEntry callback with map()-like args

- .babelrc.js
Since we use object spread inside plain objects, its behavior is identical to Object.assign, so we can get rid of the huge polyfill added by Babel in each module where spread is used. Not chunks but modules, meaning several kB of slow and bloated and unnecessary polyfills overall.
Edit: we'll enable babel loose mode globally
the only affected transforms/plugins for our browserlist:
* object-rest-spread will use Object.assign
* nullish-coalescing-operator will use == with null
> chore: enable babel loose mode

- src/_locales/en/messages.yml
- src/background/utils/db.js
- src/background/utils/update.js
- src/common/object.js
- src/common/options-defaults.js
- src/common/ui/style/style.css
- src/options/views/edit/index.vue
- src/options/views/edit/settings.vue
- src/options/views/tab-settings/index.vue
Fixes #333.
* A tri-state option to customize update notifications per script. The indeterminate state `?` means "not configured" so the current global value in Violentmonkey's settings will be used.
* A global option to ignore the per-script option. Isn't really useful normally, I'd say it's an emergency kill-switch to disable the notifications globally and ignore the per-script option.
Collateral:
* converted two related methods to async
* added value transformation function as a third parameter in `objectPick`
Didn't test it extensively yet.
> feat: per-script update notification option

- src/popup/index.js
There's an error displayed in the popup (at least in Chrome) because browser.tabs.sendMessage adds a callback to the underlying API function but our content script doesn't respond to GetPopup command so the API complains that the "port was closed". It was working before 15f33f99 fixed wrapAsync() to preserve Promise rejections whereas previously they were silently suppressed in production mode. By "suppressed" I mean they weren't printed in console so there was no way to guess that something is wrong other than manually adding a catch handler.
> fix: use sendTabCmd to suppress the error

- src/background/index.js
- src/background/utils/db.js
- src/background/utils/values.js
- src/common/browser.js
- src/options/utils/index.js
- src/options/views/edit/index.vue
- src/options/views/tab-installed.vue
- src/options/views/tab-settings/vm-import.vue
Fixes #832.
+ import Tampermonkey backup zips
+ allow drag'n'dropping backup zip onto settings page
+ indicate drop-allowed state on the import button
+ show import errors in the UI
+ convert stuff to async
P.S. should I join the non-fix commits after dragndrop into one? (2 refactors, tm import, ui report)
> feat: import from Tampermonkey and via drag'n'drop

- src/background/utils/tabs.js
- src/injected/content/tabs.js
Fixes #556.
`GM_openInTab(url, opts)`, new properties in opts:
* `pinned` *boolean*
* `container` *number*
* `0` = default container
* `1`, `2`, etc. = internal container index
* not specified = use tab's container
> feat: support containers and more options in GM_openInTab

- src/background/index.js
- src/common/consts.js
- src/injected/content/clipboard.js
- src/injected/content/index.js
- src/injected/content/inject.js
- src/injected/index.js
- src/injected/utils/helpers.js
- src/injected/web/gm-api.js
- src/injected/web/gm-wrapper.js
- src/injected/web/index.js
- src/injected/web/load-scripts.js
- src/injected/web/requests.js
Benefits:
* faster to initialize: ~10ms delta (45 -> 35) for 10 scripts on my fast desktop computer so the difference could be bigger on a slower/older laptop. 
* less memory used: 1MB delta (5 -> 4)
* proxy handler is preserved even after defineProperty
Collateral:
* fix: sandboxing of `window.onXXX` events so one script doesn't overwrite the value set in another one
* fix: unforgeable and readonly properties to mimic native behavior of `window`
* minor simplifications
~I'll test it during the next few days with more random popular scripts.~
Seems to be working fine.
You were against `Proxy` because it can't be polyfilled but I don't see why we would need that. Do you think you'll be using this repo to update the Maxthon version?
> use Proxy for sandboxing

- src/background/utils/requests.js
- src/injected/web/requests.js
Fixes decoding of blobs when the user specified only `onloadend` but no `onload`.
> fix: gmxhr handling of user-specified loadend callback

- src/injected/content/inject.js
Moves `injected-web.js` virtual entry from the page source tree into Violentmonkey tree.
Reason: page authors and those who use devtools to inspect sites may find it confusing and inconvenient that something is added to the original page tree. I put it there initially to keep it separate from the userscripts, but then a solution presented itself: if moved into a virtual subdirectory, it can be kept under the Violentmonkey entry, to which it rightfully belongs.
> ui: show injected-web.js in Violentmonkey entry in devtools

- src/injected/content/inject.js
Problem:
Scripts with some special chars like `'` in the name aren't listed under Violentmonkey tree.
This is because encodeURIComponent still implements the ancient RFC2396.
Fix:
Use fullwidth forms for more reserved characters as defined in the newer RFC3986.
> fix: substitute more special chars in sourceURL name

- scripts/webpack.conf.js
- src/common/browser.js
- src/common/util.js
- src/injected/content/clipboard.js
- src/injected/content/index.js
- src/injected/content/inject.js
- src/injected/index.js
- src/injected/utils/helpers.js
- src/injected/utils/index.js
- src/injected/web/gm-wrapper.js
- src/injected/web/index.js
- src/injected/web/load-scripts.js
Problem:
Currently VMInitInjection is called after GetInjected response which happens after the page started running its inline scripts so the globals (and prototypes that we use) may be already compromised, or the page could steal contentId and abuse it, see the team chat for more info.
Fix:
* VMInitInjection will run immediately at document_start before any page scripts.
Collateral:
* sandboxing is refactored a bit so it doesn't use unsafe Object.defineProperty from the page.
* Proxy trap for ownKeys is fixed + Symbols are handled properly
> Fix sandbox

- src/injected/content/inject.js
- src/injected/web/index.js
Follow-up to 91a6e71f to fix data passing for bridge in invoke mode: bridge.post (and its aliases invokeHost/invokeGuest) use separate parameters, bridge.onHandle uses an object { cmd, data }.
> fix: data passing for bridge in invoke mode

- src/background/index.js
- src/background/utils/preinject.js
Preinjects also for `onSendHeaders` because `onHeadersReceived` in Firefox fires *after* content scripts! And even in Chrome a site may be so fast that preinject on onHeadersReceived won't be useful (theoretically).
Makes the injection faster in Firefox by the amount of time needed for getScriptsByURL, which depends on the amount of scripts and their match/exclude patterns. In my tests the speedup was ~50ms. Someday I'll try to make it even faster using browser.userScripts API.
> fix: run preinject earlier

- src/background/utils/values.js
- src/injected/web/gm-api.js
- src/injected/web/gm-values.js
- src/options/views/edit/values.vue
Fixes #839.
The problem was in changedRemotely - it didn't check if the key is actually hooked.
There was also a null/undefined mix-up.
Collateral: reduces the amount of tab messages and their size by broadcasting only the changed values in response to GM_xxxValue, whereas previously the entire script's value storage was sent every time.
> fix: value change notifications + broadcast only changes

- src/background/utils/script.js
Fixes a very old bug with the `InjectScript` command: it always injected into the main frame.
> fix: only process the source frame in injectScript

- src/injected/web/gm-wrapper.js
When getters are invoked with incorrect `this` reference, we get `Uncaught TypeError: Illegal invocation`. This PR fixes it by passing `global` as `this` explicitly.
Minimum reproduction:
```js
// ==UserScript==
// @name        New script - violentmonkey.github.io
// @namespace   Violentmonkey Scripts
// @match       https://violentmonkey.github.io/
// @grant       GM_info
// @version     1.0
// @author      -
// @description 2/3/2020, 1:44:43 PM
// ==/UserScript==
// trigger Proxy#getOwnPropertyDescriptor so that properties get shimmed
const a = Object.keys(window);
// trigger getter with `this === gmWrapper` implicitly
console.log(document);
```
> fix: set global as this for getters

- src/common/browser.js
- src/options/index.js
Fixes #873.
The problem was two-fold:
1. prefetching of GetAllOptions wrongly unwrapped the response to `undefined` in Firefox so a second request was sent later
2. `loadData` didn't wait for the second response of options so it wasn't used when the page started in the editor mode
Collateral: added debug logs for messaging in FF
> Actually use options when starting in editor

- src/options/views/tab-installed.vue
Makes search work in dashboard after editing a script and going back to dashboard in the same tab without reloading the page, or when the script was modified in another tab, or due to auto-update.
Bonus speedup: count only visible items in batch rendering
* previously we always ran the same amount of batches even to display just one script that matched the entered search query (~90ms total time):
* now it can do everything in one timer task (~19ms total time):
Yep, that's 70ms of overhead inside Vue/browser eliminated!
> fix: search in the edited script code

- .eslintrc.js
- src/_locales/en/messages.yml
- src/background/utils/db.js
- src/background/utils/storage-fetch.js
- src/background/utils/update.js
- src/common/index.js
- src/common/storage.js
- src/confirm/views/app.vue
- src/options/index.js
- src/options/utils/index.js
- src/options/views/edit/index.vue
- src/options/views/message.vue
Fixes #876.
Main changes:
* always fetch from network and rely on browser caching  
(but the installer page still uses cache for resiliency)
* force no-cache HTTP header on script update (both manual or automatic)
* display errors for resource fetches when saving in editor (modal message) or updating in dashboard or in a notification for an updated script
Minor changes:
* keep modal message on screen while it's hovered
* preserve line breaks in modal message + show the first line in bold font
Collateral:
* ESLint: allow more props in one-line literal objects.
This one really has been driving me mad all this time because with air-bnb's limit at `4` I constantly have to break imports into three lines just because a fourth import was added. Ditto for object literals. Such a low limit would …
> update resources on script update/save and display errors

- src/common/object.js
- src/common/router.js
- src/options/utils/index.js
- src/options/views/edit/index.vue
* Displays a modal confirmation before reloading (<kbd>Ctrl-R</kbd>, <kbd>F5</kbd>) or leaving the page via history back/forward navigation. The former is a browser's built-in modal, the latter is an emulation based on pinning the current route.
* Calculates `canSave` based on deep object comparison so the real state is correctly reflected in the UI when the user undoes all changes manually.
> fix: prevent data loss on exiting/reloading editor

- src/popup/views/app.vue
The built-in new tab page in Chrome creates an injectable iframe after the user hovers the grid icon in the top right corner of the page. The same should apply to any other built-in browser pages with web iframes.
> fix: show injectable frames on non-injectable pages

- src/background/utils/requests.js
Uses 30MB for the chunk size as it looks like even 40MB is too much.
Tested on https://github.com/tophf/mpiv/issues/16
> fix: reduce chunk size to avoid bugs in Chrome

- src/injected/content/requests.js
I went with the verbose/explicit state props because my initial implementation below was too cryptic, right?
```js
req.done += msg.type === 'loadend' && (1 + ((numChunks || 1) === 1)) + !!msg.isLastChunk;
if (req.done === 2) delete requests[id];
```
> fix: chunked response may be sent in `progress` event

- src/background/utils/options.js
Turns out changing an option inside an object like `filtersPopup` resets the entire object when `updateOptions` command is sending back the changes in an object like `filtersPopup: {option: value}` so objectSet() was overwriting the entire filtersPopup object with this mini-object!
> fix: flatten key path to preserve option's parent

- src/injected/content/inject.js
The bug surfaced when there were no scripts at `document-start`.
> fix: ensure ScriptData info is sent

- src/_locales/en/messages.yml
- src/background/utils/requests.js
- src/confirm/views/app.vue
- src/injected/index.js
* Fixes tracking of `file://` URLs in Firefox 68+ as it disabled fetching of such URLs in extension pages due to [CVE-2019-11730](https://www.mozilla.org/en-US/security/advisories/mfsa2019-21/#CVE-2019-11730).
* If the source tab was inactive, the installer tab will be inactive too.
* Switched to `javascript:void 0` to cancel the request.
* Moved `bypass` to `cache`.
* Refactored the onBeforeRequest listener by splitting out the async part and flattening nested conditions.
> fix: [FF68+] track local file URLs in script installer

- src/common/ui/style/style.css
- src/common/util.js
- src/injected/web/gm-api.js
- src/injected/web/gm-values.js
- src/options/views/edit/values.vue
Error state is shown on the `Save` button in order not to frighten the user by repeated reddening of the huge textarea while they type. The button also gets disabled on error so it can't be pressed until the error is fixed.
The values are properly parsed as JSON now so the spaces are trimmed, for example. Previously `     "foo"   ` would save all this unnecessary space. There was also a trivial UI bug that an all-space value like `      ` wouldn't be recognized as an attempt to delete the value (it was properly deleted though internally so it vanished on reopening of the editor).
I've also "undeprecated" simple types in storage (`n`, `b`, `s`) because there should be no need to re-encode everything via JSON. Ideally, I want to store all values directly so numbers are stored as numbers, …
> feat: prettify JSON value, show parsing errors

- package.json
- src/common/browser.js
- src/common/ui/code.vue
- src/options/views/edit/help.vue
- src/options/views/edit/index.vue
- src/options/views/edit/settings.vue
- src/options/views/edit/values.vue
- src/options/views/script-item.vue
- yarn.lock
* Fixes #919: auto-refresh values in editor.
* Fixes #922: actually define match-highlight color.
* Feature: open editor on clicking the script icon in the dashboard
* update CodeMirror
* Limited the global codemirror keydown listener to the code panel. Previously we used it in other panels to enable <kbd>Esc</kbd> key to return to the code panel. Now it's handled by switchPanel.
* keyboard accessibility: navigate in value list via <kbd>Tab</kbd>
* keyboard accessibility: <kbd>Ctrl-Del</kbd> to delete the value focused by the above method
* keyboard accessibility: <kbd>Alt-PageUp/Down</kbd> to switch code-settings-values-help panels
* Fixed the `?` tab so it shows columns in FF: turns out the new spec edition ignores table elements.
> editor tweaks and accessibility

- src/options/views/edit/index.vue
It was broken in 796371a7 (2.12.5)
> fix: save all custom props in editor

- src/common/options.js
Follow-up to 3733bb19.
The bug manifested itself in the dashboard when trying to change filtering options.
> fix: unpack flattened data in updateOptions()

- src/injected/web/gm-wrapper.js
This is a cosmetic change.
When using `bind` the functions will keep their `[native code]` body so there's no need to patch `toString`. Originally it was patched only for GM_xxxx API, then I added patching of sandboxed wrappers when they were using arrow function syntax, which is no longer needed now.
> refactor: use native bind for sandboxed functions

- src/background/index.js
- src/background/utils/popup-tracker.js
- src/background/utils/preinject.js
- src/injected/content/index.js
- src/injected/content/inject.js
- src/injected/web/index.js
The complementary feature to early injection in Chrome, this one is using Firefox's browser.contentScripts API to pass the script data directly and thus implement the _real_ `document_start` for page mode scripts in Firefox.
Content mode seems to require more trickery (maybe rewriting `InjectionFeedback`) so I don't want to do it in this simple PR. The content mode gets somewhat faster anyway because the data is received earlier now.
Related: #374, #420.
* sourceURL can't use normal space for grouping
* FF bug workaround for sourceURL
> Use contentScripts API in FF + various fixes/tweaks

- src/options/views/app.vue
- src/options/views/tab-settings/index.vue
This is a trivial cosmetic change to offload the main options block so it'll look like this:
I've enabled keep-alive on the component switcher as there seems to be no need to rebuild the state. Maybe we could switch to the same component switching in the editor instead of its currently hardwired switcher which is overly verbose and thus not easy to extend/maintain because it needs explicit managing of the switch state.
> ui: group settings for popup/icon in a new section

- src/_locales/en/messages.yml
- src/background/index.js
- src/common/options-defaults.js
- src/injected/content/index.js
- src/injected/web/index.js
- src/options/views/tab-settings/index.vue
Tried several approaches, ended up with a predefined object in options: 
```js
expose: { // use percent-encoding for '.'
'greasyfork%2Eorg': true,
'sleazyfork%2Eorg': false,
},
```
For #959 the info might be something like this
> To facilitate script installation Violentmonkey may expose the version of an installed script when "Expose installed version on userscript catalog sites" option in advanced settings is enabled for these popular sites: https://greasyfork.org (enabled by default) and https://sleazyfork.org (disabled by default). The enabled sites will be the only ones where Violentmonkey makes its presence explicitly apparent by exposing this information. Other than that, the only way for an arbitrary site to guess Violentmonkey might be present would be for you to have a …
> feat: make exposing via window.external optional

- src/_locales/en/messages.yml
- src/background/utils/hotkeys.js
- src/background/utils/requests.js
- src/background/utils/tabs.js
- src/common/browser.js
- src/common/index.js
- src/confirm/views/app.vue
- src/popup/index.js
- src/popup/style.css
- src/popup/views/app.vue
Fixes #961.
The warning in the popup is displayed at the bottom because the popup doesn't contain any potentially dangerous actions in itself. Opening an editor will switch windows which is a [hopefully] sufficient hint.
> fix: openerTabId can't be used across incognito

- src/background/utils/preinject.js
- src/common/consts.js
- src/injected/web/gm-wrapper.js
- src/injected/web/index.js
Fixes #966 (only in `@grant none` script of course).
The actual execution of script code is moved into wrapGM to avoid transferring and unpacking of arguments. Any objections? Maybe wrapGM should be renamed?
> fix: set `this` to `window` for grant-none scripts

- src/background/sync/base.js
- src/background/sync/index.js
- src/background/sync/onedrive.js
- src/background/sync/webdav.js
- src/background/utils/storage-fetch.js
- src/common/util.js
- src/options/views/tab-settings/vm-sync.vue
fix #976 
- Send internal requests with `fetch`. This affects all requests in Violentmonkey except those sent by `GM_xmlhttpRequest`.
- Omit cookies for WebDAV sync service, bypassing logout/login CSRF protection in NextCloud/OwnCloud. Since we always sent authentication header explicitly in the background, there is no need to worry about CSRF.
- Reschedule sync process when sync service is changed.
- Small tweaks on style, to keep the space after colon in languages like English.
> Omit cookie in WebDAV requests

- src/common/ui/code.vue
Observed in this scenario: open the editor, select something, press the "findNext" hotkey (F3 or Ctrl-G in Windows), press it again.
The second time will wrongly show the browser built-in search dialog.
> fix: register onKeyDownToggler on init

- src/background/utils/preinject.js
- src/common/consts.js
- src/injected/web/gm-wrapper.js
- src/injected/web/index.js
Turns out Tampermonkey sets `this` to the miniwrapper so I'm reverting d4b6805 thus restoring the old VM's behavior. TM also doesn't define unsafeWindow but since no one complained about this in VM I'm leaving it unchanged.
AFAICT, either behavior is fine and compatible with userscripts in grant-less mode but a) my improvement wasn't improving anything since no one expected it anyway and b) it was adding complexity to the code.
> revert setting `this` to `window` for grant-none scripts 

- src/_locales/en/messages.yml
- src/background/utils/db.js
- src/injected/content/bridge.js
- src/injected/content/index.js
- src/injected/content/inject.js
- src/popup/index.js
- src/popup/style.css
- src/popup/utils/index.js
- src/popup/views/app.vue
Turns out most of existing users are still using the `page` injection mode instead of `auto` which is the default one since dea7de01defb3cfcada84593f0c2837ee5885569 in 2.12.2. It means we still don't help our longtime Firefox users who are affected by the Firefox bug that applies page CSP to our script elements.
This PR forcefully switches from `page` to `auto` when upgrading from 2.12.7 or older in Firefox.
> fix: switch page->auto mode on upgrade from pre-2.12.8

- src/common/ui/code.vue
- src/common/ui/style/style.css
Support basic autocomplete using `Ctrl-Space`.
The main logic comes from CodeMirror's auto complete: https://codemirror.net/demo/anywordhint.html
UI on violentmonkey's script editor:
> feat: [editor] support autocomplete

- src/_locales/en/messages.yml
- src/options/views/edit/values.vue
Adds an `All` button in the value editor to edit the entire storage as a JSON object. This allows to import/export the entire storage to simplify transferring of individual scripts+data, also from/to Tampermonkey.
> feat: button to edit entire value storage of a script

- src/background/index.js
- src/background/utils/icon.js
In FF, tab injection sometimes starts before the tab receives its `url` internally. So our `GetInjected` sets the badge, then url is assigned internally and the badge is reset. Fixes #1037.
> fix: workaround for badge update bug in FF

- package.json
- src/common/ui/code.vue
- yarn.lock
Closes #1019
It replaces PR #1022. 
The actual CodeMirror highlight html/css logic is moved to a separate package.
https://www.npmjs.com/package/codemirror-js-mixed
> editor - highlight html/css with  javascript-mixed

- src/injected/web/gm-wrapper.js
Restores the fix for #765 which was lost in a2cb1c67.
> fix: restore wrappedJSObject workaround

- src/background/utils/tester.js
- test/background/tester.test.js
Closes #1044
* `@include`, `@exclude`: case-insensitive like GM4/TM, but not like extensions API include_globs or exclude_globs
* `@match`, `@exclude-match`: only host part is case-insensitive like extensions API
> fix: case-sensitivity adjustments for url matching

- src/_locales/en/messages.yml
- src/background/utils/tabs.js
- src/common/browser.js
- src/common/options-defaults.js
- src/options/views/edit/index.vue
- src/options/views/tab-settings/index.vue
- src/popup/views/app.vue
Fixes #1058.
The option is added in general section:
`[x] Open editor from popup in a new window`
The size/position of such a separate window is remembered automatically. In browsers that don't support chrome.windows.onBoundsChanged (only Chrome 86+ at the moment) a tooltip is displayed:
`Editor window position will be remembered only on resizing or saving`
> feat: option to open editor in new window from popup

- src/common/ui/code.vue
- src/common/ui/style/style.css
Fixes #1067.
CodeMirror no longer uses the bad pure green `#00ff00`, it switched to `#00bb00` so we can revert to the `default` theme now.
> fix: use the default CM theme in default light mode

- src/injected/web/gm-wrapper.js
This was bad... RC was reusing `window` of the first script in all subsequent ones.
> fix: always set each script's `window` to its own wrapper

- src/_locales/en/messages.yml
Now that thanks to d1539d3 themes can be used as is, without editing them, this PR adds a simple how-to:
> Custom options for CodeMirror and addons in JSON object like `{"indentUnit":2, "smartIndent":true}` however note that some of them may not work in Violentmonkey. See [full list](https://codemirror.net/doc/manual.html#config). To use a custom CodeMirror theme, specify its file name like `"theme": "3024-day"` here and paste the [actual theme's CSS](https://github.com/codemirror/CodeMirror/tree/master/theme) in "Custom Style" input below.
> feat: add a note in UI about using custom CM themes

- src/background/utils/tester.js
- test/background/tester.test.js
* fix: some [tlds](https://publicsuffix.org/list/public_suffix_list.dat) have `-`
* fix: `tld` in patterns must be only lowercase
* added tests for these problems
* simplified hostMatcher a bit so there's only one toLowerCase() in the returned function
> fix: case sensitivity edge cases + hyphens in TLD

- src/common/ui/code.vue
There is no `CodeMirror-wrap` in the codebase.
> fix: dark mode theme of CodeMirror

- src/common/ui/code.vue
Turns out a parent `.CodeMirror` should be present in the selector e.g. `.CodeMirror .CodeMirror-selected` like it was before #1079, otherwise the light theme's CSS was applied to some things like text selection.
> fix: restore dark theme CSS specificity

- README.md
- gulpfile.js
- package.json
This is a proposal workflow for self-hosted releases or beta releases that can be published more frequently and tested by power users.
Since we don't have a lot of developers and we are unlikely to develop many features concurrently, I don't think it necessary to have multiple channels like in tremendous projects as Chrome and Firefox. So this proposal is actually prereleases + milestone like releases.
1. version numbers
Web extensions do not support semver (maybe supported by some, but not all), we can use more dot separated numbers as version numbers. An extra number is added to make this work.
For example, say `2.12.7` is a release, the following prereleases can be `2.12.7.1`, `2.12.7.2`, etc. And when it comes to a next release, the extra number can be removed (or reset to 0 and …
> Proposal: beta releases

- src/_locales/en/messages.yml
- src/common/ui/code.vue
- src/options/views/edit/index.vue
* fix: add placeholders on pasting/duplicating/sorting/etc.
Also speed up it a little by using CodeMirror's generation instead of comparing the re-assembled code string which can be long. This also avoids stressing the garbage collector after each change.
* fix: catch regexp compilation error in Ctrl-F and show it as `title`.
Uses the standard DOM `title` which is somewhat unusual but I think it makes sense to be different from the other UI tooltips.
> fix: add placeholders on pasting/duplicating/sorting/etc.

- src/background/utils/db.js
- src/common/util.js
Fixes #1087.
The advantage is that it's specification-compliant and a single crypto.getRandomValues is faster than multiple Math.random.
The only drawback is that we lose 6 bits of randomness out of 96 we had previously but I think we can live with that :-)
> fix: use RFC algo for UUID

- src/_locales/en/messages.yml
- src/background/utils/update.js
- src/common/util.js
- src/options/views/script-item.vue
* Fixes #1090.
* Restores the correct tooltip with the error details (the `error.url` was lost in 80cde6da0ac731d5a3d13aaedfe2c67db2df0d8a)
* ~shows an instruction how to open devtools of the background page to debug the network problems:~
<details>
In Firefox the instruction is slightly different, it also doesn't allow extensions to open `about:debugging`.
</details>
> fix: accept any MIME type on update check + show error info

- src/common/ui/code.vue
- src/common/ui/toggle-button.vue
- src/options/views/edit/index.vue
Several tweaks/fixes for bugs or quirks that I wanted to fix a very long time ago, trivial as they are:
* The panel is now at the bottom so it doesn't shift layout - it was distracting and disorientating. An alternative solution might be to use absolute positioning but that would cover the very first line.
* find/findNext/findPrev will continue from the current position if you change it - just like in other apps.
* findNext/findPrev won't steal focus from CM and if you closed the search UI after setting the text to search then the UI won't even show up for these commands - just like in all other apps.
* Revealing next match that is out of viewport will center it - so we can see the surrounding context.
* Fixed findFillQuery so it won't erase the current search text when invoked with …
> fix: tweak and improve find/replace

- src/common/ui/style/style.css
- src/options/style.css
- src/options/views/app.vue
- src/options/views/tab-installed.vue
* always show menu at the top
* start hiding authors/dates at 500px (previously at 767px)
* start hiding search at 319px (previously at 767px), in 320-500px its width is automatically reduced
> style: retain more parts of UI in compact mode

- src/background/index.js
- src/background/utils/cache.js
- src/background/utils/db.js
- src/background/utils/popup-tracker.js
- src/common/browser.js
- src/common/index.js
- src/common/load-script-icon.js
- src/common/options.js
- src/common/ui/setting-check.vue
- src/common/ui/setting-text.vue
- src/options/index.js
- src/options/views/script-item.vue
- src/options/views/tab-installed.vue
- src/options/views/tab-settings/index.vue
- src/popup/index.js
- src/popup/utils/index.js
- src/popup/views/app.vue
It bugged me for a while that the popup is initially rendered with an empty script list for a fraction of a second. So, I've tried to find a way to improve it. The result is that now all UI loads faster by fetching the data directly from the background page which is synchronous.
Additional speedups:
* dashboard: replaced the very slow `cache2blobUrl` with a data URI.
* editor when launched from popup: `GetData` sends only the edited script at first
* popup: `SetPopup` data is prefetched by the background script when the popup starts loading.
The no longer needed prefetch for options in browser.js was removed.
> feat: faster load of popup, editor, dashboard

- src/options/index.js
Firefox doesn't show dashboard tab favicon so this PR adds one explicitly.
> feat: show dashboard favicon in Firefox

- src/options/index.js
- src/options/views/script-item.vue
* Using real size 38px and 32px for the icons instead of 42px and 28px to make them look crisp on a single density display.
* Using 128px on HiDPI
Old | New
-|-
> feat: crisp dashboard icons

- src/common/ui/code.vue
Fixes #1127.
* greenish string colors
* desaturated comments
* regexps have their own color different from template strings
This is how it looks now:
> feat: differentiate regexps from strings + tweak colors

- src/_locales/de/messages.yml
- src/_locales/el/messages.yml
- src/_locales/en/messages.yml
- src/_locales/es_419/messages.yml
- src/_locales/fi/messages.yml
- src/_locales/fr/messages.yml
- src/_locales/hr/messages.yml
- src/_locales/id/messages.yml
- src/_locales/it/messages.yml
- src/_locales/nl/messages.yml
- src/_locales/pl/messages.yml
- src/_locales/pt_BR/messages.yml
- src/_locales/pt_PT/messages.yml
- src/_locales/ro/messages.yml
- src/_locales/sk/messages.yml
- src/_locales/sr/messages.yml
- src/_locales/tr/messages.yml
- src/_locales/uk/messages.yml
- src/_locales/vi/messages.yml
- src/background/utils/db.js
- src/injected/content/inject.js
- src/options/views/edit/settings.vue
- src/options/views/tab-settings/vm-import.vue
* implement `@run-at document-body`, related: #1137
* add the missing space in labelRunAt for letter-based languages
1. How do I/we update files on transifex for this change? I can do it manually I guess but I'd prefer to upload in one click.
2. Maybe we could instead just check for unicode range of the message in `i18n` and add the space after ASCII colon `:` automatically?
> implement run-at: document-body

- src/background/index.js
- src/injected/content/index.js
- src/injected/content/inject.js
- src/injected/web/bridge.js
- src/injected/web/gm-api.js
- src/injected/web/index.js
Also:
* run `document-idle` content mode scripts after `document-idle` page mode scripts (previously they ran at document-end)
* run each `document-idle` script after its own individual setTimeout so that several big scripts don't create a super long task.
* run `setTimeout` in background context for reliability
> feat: implement document-body for content mode

- src/popup/style.css
- src/popup/views/app.vue
- src/resources/svg/more.svg
Fixes #1000.
* Homepage if present
* Remove (or Restore)
I wonder if showing the version number at the top of the new menu would make sense? As for update check, it would require quite a few changes apparently so ain't gonna add it here.
> feat: show extras menu in popup (remove + homepage)

- src/background/index.js
- src/background/utils/preinject.js
- src/common/cache.js
I *think* this PR fixes #1159, specifically:
> when I disable or enabled scripts it seems that violentmonkey didnt seems to enable or disable them.
I even used the flip button from violentmonkey and disable all scripts with that, and ctrl-F5 the page but it seemed that violentmonkey got stuck in its last stage and the scripts were run again, when they should have not because they were disabled.
The code is trivial with the only nuance that a separate cache is created for preinject data to simplify enumeration of values because the main cache may have thousands of items.
> fix: explicitly clear preinject cache when DB changes

- src/options/views/edit/settings.vue
+ align editor settings
+ split into multiple columns on wide displays
+ auto-fit textarea height
+ remove tooltips on textareas because their labels already indicate `@key`
> ui: align editor settings

- src/_locales/en/messages.yml
- src/background/utils/script.js
- src/common/ui/code.vue
- src/confirm/views/app.vue
Fixes #1121
Narrow window | Wide window
-|-
Clicking the `(i)` icon collapses the lists and makes their titles clickable to display only the clicked list:
I don't want to store this state persistently via `setting-check` because the entire point of showing the lists in the installer is to make them obvious at a glance, especially important if the script has the metablock somewhere down the code or it adds spaces to "hide" the urls.
> feat: show structured info in install confirm ui

- src/confirm/views/app.vue
* auto-retry loading deps in installer 2 times, tested by blocking a url via `etc/hosts`
* expose "data-type" attr & make `@antifeature` red, demo: https://greasyfork.org/en/scripts/417327-antifeature-test
> feat: improve installer

- src/background/utils/preinject.js
Fixes problem: Preinjects do not refresh in Firefox.
The cache for preinject contains promises but the checks do not wait for them to be resolved. As a result the checks always fail.
> fix: check preinject after promise resolved

- src/background/index.js
- src/background/utils/db.js
- src/background/utils/icon.js
- src/background/utils/popup-tracker.js
- src/common/load-script-icon.js
- src/common/storage.js
- src/options/index.js
- src/options/views/script-item.vue
- src/popup/index.js
- src/popup/utils/index.js
- src/popup/views/app.vue
Icons now load instantly (in Chrome at least).
* icons will be loaded from db `cache` and used in dashboard/popup as `data:` to avoid network requests
* if an icon isn't in cache for whatever weird reason, a new command is added: `GetImageData`
* `data:` icons will be used directly without verification because I don't think I ever saw a broken one
* `transform` parameter added to `getMulti` method in `storage`
> feat: load icons from storage cache

- src/popup/views/app.vue
I guess the popup should be closed when a command is clicked, which is the default behavior of most menus.
> fix: close popup on command click

- src/background/index.js
- src/background/utils/preinject.js
- src/common/cache.js
In Firefox, when a content script registration is removed from our cache because of expiration, it won't be unregistered, leading to multiple registrations for a URL and script updates cannot take effect any more.
This PR adds an `onDispose` callback to explicitly dispose every cached registration when it is removed from cache.
> fix: ensure content script to be unregistered

- src/background/utils/hotkeys.js
- src/background/utils/tabs.js
- src/popup/views/app.vue
Pressing a hotkey assigned in `chrome://extensions/shortcuts` to create a new script will use the active tab's url now.
> fix: read active tab's URL for newScript hotkey

- src/_locales/en/messages.yml
- src/common/options-defaults.js
- src/common/ui/setting-check.vue
- src/options/views/script-item.vue
- src/options/views/tab-installed.vue
Addresses #1135 #1210 #1221.
I didn't want to implement it initially because it seemed like a 100% CSS customization but now I kinda do.
* The table layout needs a clickable name because a) this is how such layout usually works and b) the edit button is too far from the script name. Without supporting this event internally the CSS has to stretch the edit button over the name button which is a dirty hack.
*  VM isn't Stylus so it doesn't have a quick way to toggle the style.
* A user might want to switch modes for a quick overview of all the scripts at once, then switch back.
> feat: options for table view and single-column mode

- src/injected/content/index.js
Fix exposure of `window.external.Violentmonkey` in Firefox.
> Fix exposure of window.external.Violentmonkey in Firefox

- src/background/utils/requests.js
- src/injected/web/requests.js
Fix #1229 indeed.
In #1068 the `xhr.response` is sent multiple times when `progress` event is listened, and a partial response is cached in `raw`, leading to incomplete `req.response` and parse error for `json` type.
In this PR the response is ensured to be sent exactly once and concatenated as `req.raw` for all content types except `text`, including `document` and `json`.
I think `req.raw` is not necessary for `text`, `json` and `document` types as they are all regarded as `text` in the background, but we can make use of it to allow data to be handled by the same function `parseData`. Maybe we should handle all data as blob or arraybuffer in the background to support super large responses.
> fix: send chunks exactly once

- src/injected/web/requests.js
fix #1240
Otherwise empty string data `[{ cls: 'string', value: '""' }]` becomes `[null]` and `decodeBody` throws.
> fix: keep empty strings as params in requests

- src/popup/style.css
- src/popup/views/app.vue
This is a follow-up to #1243 .
Before:
- There are two independent focused items, one by keyboard and the other by mouse.
After:
- There is only one focused item which can be switched by either keyboard or mouse.
I guess this makes it closer to a native menu.
> fix: improve keyboard navigation

- src/_locales/en/messages.yml
- src/background/utils/icon.js
- src/common/options-defaults.js
- src/options/views/tab-settings/index.vue
Fixes #1301.
* **Non-customized state:**
* **When customized, `reset` is shown:**
> feat: customizable badge colors

- src/common/ui/index.js
- src/options/views/edit/index.vue
Adding a new row so the user can click it and type, just like in an empty textarea:
> feat: add empty row to editor>settings>textarea

- src/_locales/en/messages.yml
- src/common/options-defaults.js
- src/options/index.js
- src/options/style.css
- src/options/utils/index.js
- src/options/views/app.vue
- src/options/views/script-item.vue
- src/options/views/tab-installed.vue
Fixes #1320
Fixes #1281.
commit | ui
-|-
feat: show total number of scripts in dashboard | ![image](https://user-images.githubusercontent.com/1310400/126908324-163ac423-435c-4425-ace9-ec731c7bce8c.png)
feat: show execution order in dashboard<br>I'm not sure we need this one, WDYT, @gera2ld? | ![image](https://user-images.githubusercontent.com/1310400/126986028-a8c2a77d-0f42-4f75-aad4-114339372473.png)
> Script numbers

- package.json
- src/background/utils/requests.js
- src/common/browser.js
- src/common/ua.js
Fixes #1167.
`Cookie` and `Set-Cookie` HTTP headers for incognito tabs in Chrome or all tabs in FF will use their own cookie store. Chrome has two (default and incognito), FF may have many additional containers.
Could you help test it, please, @AlttiRi, @brian6932? Here's a dev version: [dev.zip](https://github.com/violentmonkey/violentmonkey/files/6769437/dev.zip)
> feat: separate cookies in gmXHR per container

- src/confirm/views/app.vue
When `@antifeature` is too long, it will be cut at the right of the page.
Before:
After:
> fix: wrap long text in confirm page

- src/_locales/en/messages.yml
- src/popup/index.js
Tests the actual injectability via executeScript and displays two additional examples of non-injectable sites in popup:
* search engine site in Opera
* blocked via policies, specifically `runtime_blocked_hosts` in Chrome
Should help #1322.
I went with this simplified universal solution since we can't even reliably detect if the current site is actually the default search engine in Opera, and we don't want to add a browser-specific kludge for such an edge case anyway.
> feat: show more examples of injection failures

- src/background/utils/requests.js
- src/common/util.js
Fixes #1329.
@AlttiRi, please test it as I don't remember sites with such headers.
> fix: encode webRequest's responseHeaders to utf8 for GMxhr

- src/background/utils/requests.js
- src/background/utils/storage-fetch.js
- src/common/storage.js
- src/common/util.js
- src/confirm/views/app.vue
- src/injected/content/requests.js
- src/injected/utils/helpers.js
- src/injected/web/gm-api.js
- src/injected/web/requests.js
- test/mock/polyfill.js
* Firefox can send Blob/File/ArrayBuffer directly via extension messaging, also in incognito tabs. Now, downloading huge files (100MB or more) takes just a couple of seconds. Previously, we used chunks because FF could block fetching of blobs on a page with a strict CSP.
* FileReader is much faster than buffer2string: 2x in Chrome, 10x in Firefox
* Using base64 makes the internal message size 1.5x smaller at least in Chrome because Chrome encodes our buffer2string's result to UTF-8, which increases the size and is slow. Now with base64 Chrome doesn't re-encode.
I've also renamed `details` to `opts` to indicate these are user options of GMxhr's call. I regularly got confused about `details` as it can conceptually refer to a response or a request or anything for that matter.
> speedup: GMxhr in FF + use FileReader for internal encoding

- src/background/utils/tabs.js
- src/common/browser.js
* **feat: reuse an existing editor when editing a script** - a couple of times I accidentally opened a second editor after forgetting I had unsaved changes in the first one
* **fix: disable windowed editor in FF before v64** - cookieStoreId in windows.create() is supported since FF64 and a workaround is too convoluted to add it for such an ancient version
> feat: reuse an existing editor when editing a script

- .eslintrc.js
- src/common/consts.js
- src/common/index.js
- src/common/object.js
- src/common/util.js
- src/injected/content/index.js
Our .browserslistrc targets old browsers so the compiled code for {...objSpread} uses babel's polyfill that calls methods like `Object.assign` instead of our safe `assign`
Ideally, `eslint-plugin-compat` should be used but I couldn't make it work.
> fix: forbid {...objSpread} in injected/* via eslint

- src/common/util.js
How to test: click the install button in https://greasyfork.org/scripts/430515 and when VM's installer shows up, open devtools console.
@JasonBarnabe, do you think this solution (sending an `Accept` header only with JS types) is universal? Otherwise maybe you could return empty content with 404 status if we add some special header to the request?
@gera2ld, I'm not sure this PR is even necessary because the only bad thing is the spam in console, and it happens only when a dependency on greasyfork was deleted so it responds with a `404` html page.
P.S. I have another solution: 50 dense lines of stripping the header via webRequest API, but it's probably an overkill.
> fix: accept only JS to disable prefetch and CSP errors

- src/injected/content/index.js
- src/injected/web/index.js
- src/popup/views/app.vue
https://github.com/Tampermonkey/tampermonkey/issues/1307
The menu command can be executed by clicking any mouse button or pressing <kbd>Space</kbd> or <kbd>Enter</kbd>, with any modifiers. All this info is passed to GM_registerMenuCommand's function as KeyboardEvent or MouseEvent accordingly.
Test script:
```js
// ==UserScript==
// @name        test GM_registerMenuCommand event
// @match       *://*/*
// @grant       GM_registerMenuCommand
// ==/UserScript==
GM_registerMenuCommand('test', (e = {}) => {
const isMouse = e.button != null;
alert([
e.shiftKey && 'Shift-',
e.ctrlKey && 'Ctrl-',
e.altKey && 'Alt-',
e.metaKey && 'Meta-',
isMouse
? `btn${e.button}`
: `${e.key === ' ' ? '" "' : e.key} / ${e.keyCode}`,
!isMouse && e.code !== e.key && ` / ${e.code}`,
].filter(Boolean).join(''));
}); …
```
> feat: pass DOM event to GM_registerMenuCommand function

- src/background/sync/base.js
- src/background/sync/dropbox.js
- src/background/sync/googledrive.js
- src/background/sync/index.js
- src/background/sync/onedrive.js
Also, the request to redirect_uri will be blocked sooner so it won't see the token.
This fix may resolve https://github.com/kiwibrowser/src.next/issues/278.
@KaKi87, you can try the attached development build of the extension: [dev.zip](https://github.com/violentmonkey/violentmonkey/files/6996650/dev.zip) (v2, reuploaded).
> fix: use webRequest to intercept tokens

- scripts/plaid.conf.js
- scripts/webpack.conf.js
- src/background/index.js
- src/common/browser.js
- src/common/handlers.js
- src/common/storage.js
- src/common/ua.js
- src/confirm/index.js
- src/injected/index.js
- src/manifest.yml
- src/options/index.js
- src/popup/index.js
1. The startup time is faster for ~5ms because Proxy works on demand.
The overall time spent inside the module has marginally decreased (from 7ms to 5ms) judging by performance profiler while opening VM's dashboard page.
Now there's no need to manually add new methods because the meta object lists just the special cases - non-asynchronous and overridden methods.
2. browser.js is embedded as a module because executing each separate content script has internal overhead. The overall file size decreased a little because the actual contents of browser.js is just 0.9k, the rest 1.2k was webpack's bootstrap. Now browser.js is embedded into two files: injected.js and common.js.
Embedding it allowed some deduplicating of webpack/plaid configs.
> refactor: use Proxy for `browser`, embed it as module

- src/_locales/en/messages.yml
- src/common/options-defaults.js
- src/options/views/tab-settings/index.vue
- src/popup/style.css
- src/popup/views/app.vue
* The iframe scripts aren't affected, they're still listed in one combined menu.
* The `>` icon is moved to the left since all persistent icons are shown there
* The background color of the active menu is one notch stronger
* The last menu has a dashed border in collapsed state to separate it from the footer
> feat: option to group disabled scripts in popup

- src/_locales/en/messages.yml
- src/background/utils/db.js
- src/options/views/edit/index.vue
- src/options/views/edit/settings.vue
- src/options/views/tab-settings/vm-import.vue
The label is `Run in frames` which is the opposite of `noframes` because it seems easier to understand than Tampermonkey's "Run only in top frame". People normally say "frame" to refer to an `<iframe>` or `<frame>` element, we don't normally call the main page "top frame", it's an internal term from the extension API or from other low-level internals/specifications.
> feat: customizable @noframes in editor settings

- src/background/index.js
- src/background/utils/cache.js
- src/background/utils/db.js
- src/background/utils/icon.js
- src/background/utils/preinject.js
- src/common/browser.js
- src/common/cache.js
- src/common/index.js
- src/common/object.js
- src/common/storage.js
- src/injected/content/bridge.js
- src/injected/content/index.js
- src/injected/content/inject.js
- src/injected/web/bridge.js
- src/injected/web/gm-api.js
- src/injected/web/index.js
- test/injected/gm-resource.test.js
Arguably this should fix #1353 in 99% of cases.  Memory usage won't increase by much as the most of it is spent on JS engine itself and our other variables.
Edit:
Turns out the longer caching doesn't help in case of huge `cache` or `values` because just sending them via a message takes an insane amount of time (at least in Chrome) so I've implemented separate loading of `document-start` and -body scripts/data from storage and separate injection. The rest (document-end and -idle) will be sent in the next message.
> feat: separately inject start/body scripts, cache for 1hr

- src/_locales/en/messages.yml
- src/options/views/tab-settings/index.vue
- src/options/views/tab-settings/vm-export.vue
- src/options/views/tab-settings/vm-import.vue
I think this is an improvement because it removes the repetition of `import` and `export` words in the title/buttons and combines the closely related activities in one section.
> ui: combine import/export in "Backup" section

- src/_locales/en/messages.yml
- src/background/sync/base.js
- src/options/views/tab-settings/vm-sync.vue
* show "Not configured yet" instead of sync error
* show the status in the same row to make it more noticeable
* hide "[x] Sync script status" when `None` is selected
> ui: show "Not configured yet" instead of sync error

- .babelrc.js
- .eslintrc.js
- package.json
- scripts/babel-plugin-safe-bind.js
- scripts/webpack.conf.js
- src/background/utils/preinject.js
- src/common/object.js
- src/common/safe-globals.js
- src/common/ui/externals.vue
- src/common/util.js
- src/injected/content/bridge.js
- src/injected/content/clipboard.js
- src/injected/content/index.js
- src/injected/content/inject.js
- src/injected/content/notifications.js
- src/injected/content/requests.js
- src/injected/safe-injected-globals.js
- src/injected/utils/helpers.js
- src/injected/utils/index.js
- src/injected/web/bridge.js
- src/injected/web/gm-api.js
- src/injected/web/gm-values.js
- src/injected/web/gm-wrapper.js
- src/injected/web/index.js
- src/injected/web/notifications.js
- src/injected/web/requests.js
- src/injected/web/tabs.js
- src/options/views/tab-settings/index.vue
- test/mock/polyfill.js
- yarn.lock
Profiler shows injected.js loads faster: 13ms previously, 10ms now. This is because webpack was calling its internal machinery each time the safe method was defined and used.
Production files also became ~1kB smaller.
It's hackish, but hopefully still acceptable. The only small problem I don't know how to solve is making VSCode jump to definition of such globals as `forEach`.
Edit: also fixes #1373.
> speedup: define safe globals via header injection

- src/common/util.js
- test/common/index.test.js
Add a simple test for private address ([RFC 1918](https://datatracker.ietf.org/doc/html/rfc1918), [RFC 4193](https://datatracker.ietf.org/doc/html/rfc4193)) and reserved domains ([RFC 2606](https://datatracker.ietf.org/doc/html/rfc2606)).
> feat: update isRemote

- src/background/utils/preinject.js
- src/injected/web/gm-api-wrapper.js
- src/injected/web/index.js
Fixes #1531.
* Uses a second `with` to let JS engine resolve the globals we already resolved instead of calling our Proxy's `get` trap that replicated the same behavior but much slower.
* ~Uses local variables for 16 frequently used globals like `Array` or `Math`. The only possible problem is that a userscript cannot alter the value of these globals via the standard approach like `window.Math = polyfill` as this will not change the variable.~
* Removes `with` from grant-none scripts to avoid the drop in performance
> feat: faster wrapper prop resolution

- src/background/utils/preinject.js
Fix a regression introduced by #1532 : UMD requirements are broken in pages using RequireJS when `@grant` is not none.
- Page: <https://www.skype.com/en/get-skype/>
- Script:
```js
// ==UserScript==
// @name        Test UMD require
// @namespace   Violentmonkey Scripts
// @match       https://www.skype.com/en/get-skype/
// @grant       GM_addStyle
// @version     1.0
// @require     https://cdn.jsdelivr.net/combine/npm/@violentmonkey/dom@^2,npm/@violentmonkey/ui@^0.7
// @author      -
// @description 8/9/2022, 6:17:32 PM
// ==/UserScript==
console.log('ok');
```
> fix: set define to undefined even when grant is not none

- src/injected/content/requests.js
_Disclaimer: I am not well versed in webexts, so I am not sure if this is the proper fix._
After update to `v2.13.1`, I noticed that some functionality with `GM_xmlhttpRequest` was broken.
(I did test latest master commit and latest beta release, both had the issue as well.)
In particular, this simplified excerpt stopped working:
```js
var url = "...";
var formData = new FormData();
formData.append("..", var1);
formData.append("..", var2);
formData.append("..", var3);
formData.append("..", var4);
GM_xmlhttpRequest({
method: "POST",
url: url,
data: formData,
onload: function(r) {
...
}
});
```
leading to the following error in the browser console:
```
Error: Not allowed to define cross-origin object as property on [Object] or [Array] XrayWrapper
```
at the following line of code …
> fix: HttpRequest msg.data context

- src/background/index.js
- src/background/sync/index.js
- src/background/utils/cache.js
- src/background/utils/clipboard.js
- src/background/utils/db.js
- src/background/utils/icon.js
- src/background/utils/message.js
- src/background/utils/notifications.js
- src/background/utils/options.js
- src/background/utils/popup-tracker.js
- src/background/utils/preinject.js
- src/background/utils/requests.js
- src/background/utils/script.js
- src/background/utils/storage.js
- src/background/utils/tab-redirector.js
- src/background/utils/tabs.js
- src/background/utils/tester.js
- src/background/utils/update.js
- src/background/utils/values.js
- src/common/browser.js
- src/common/index.js
Instead of manually maintaining the list in `commandsForSelf`, which is error-prone and easy to forget, introducing two methods  addOwnCommands and addPublicCommands, which explicitly indicate the security scope.
> fix: more reliable commandsForSelf check

- scripts/plaid.conf.js
- src/options/views/tab-installed.vue
Fixes #1632 and adds a bonus for non-bugged browsers: no style recalc due to a getComputedStyle call.
This PR conflicts with the recycle bin PR, so which one will we merge first, @gera2ld?
> fix: calc number of columns resiliently

- .eslintrc.js
- scripts/webpack-util.js
- src/background/utils/db.js
- src/background/utils/preinject.js
- src/background/utils/script.js
- src/background/utils/values.js
- src/common/cache.js
- src/common/consts.js
- src/common/options-defaults.js
- src/common/safe-globals-shared.js
- src/common/safe-globals.js
- src/common/util.js
- src/injected/content/bridge.js
- src/injected/content/cmd-run.js
- src/injected/content/gm-api-content.js
- src/injected/content/index.js
- src/injected/content/inject.js
- src/injected/safe-globals.js
- src/injected/web/gm-api-wrapper.js
- src/injected/web/index.js
- src/options/views/tab-settings/index.vue
- src/popup/index.js
- src/popup/views/app.vue
- src/types.d.ts
- test/mock/polyfill.js
While fixing the bug described in the title I did a few more fixes/speedups and while doing that I refactored injection-related code considerably for which I'd like at least a cursory review from you, @gera2ld.
* preinject.js now reuses results of each individual `preparedScript` if it's still cached
* all injection-related consts are extracted to safe-globals-shared.js because importing a lot of these consts in like every file has been an increasing PITA for a while.
> fix: safe-guard window.vmXXX initializers + speedup

- src/popup/style.css
- src/popup/views/app.vue
Fixes #1663.
Testing:
1. set OS font zoom to 200% or more
2. optionally resize the browser window's top border to the middle of the screen - to halve the available height for the popup
3. make sure you have a lot of scripts in the list or use the [html from the report](https://github.com/violentmonkey/violentmonkey/files/10088142/Copy.outerHTML.txt).
> fix: popup + big font zoom + small display

- src/common/index.js
URL in meta may be set to an invalid value to enforce disabling of the automatic updates e.g. GreasyFork sets it to `none` when the user installs an old version. We'll show such script as non-updatable.
Fixes #1680.
> fix #1680: ignore invalid update URL

- src/popup/style.css
- src/popup/views/app.vue
fixes #1736
Works in my emulator, but maybe it doesn't in a real phone? @gera2ld, please test.
I tested only in Firefox because Kiwi doesn't start in the emulator.
> fix: set popup height to 100% in mobile browsers

- src/options/index.js
- src/options/utils/index.js
- src/options/views/tab-settings/vm-import.vue
Importing a few megabyte zip that has many differences to the current database was very slow if the script list was already shown. It took several seconds when going from 60 to 130 scripts on my fast desktop computer, which means it would be a minute on a mobile phone. With throttling this operation takes just ~1 second as tested on the same old database in a clean install.
P.S. When adding `importing` to `store` I've also moved 3 needlessly(?) separated props from index.js.
> fix: speed up imports by throttling render

- package.json
- src/common/ui/style/style.css
- src/options/style.css
- src/options/views/app.vue
- src/options/views/edit/index.vue
- src/options/views/tab-installed.vue
- yarn.lock
fix #1729
Changes:
- The script list has a max-height of `100vh` and is still scrollable. So on small screens, the total height will be `height of header + 100vh`, so we can trigger a body scroll event and hide the toolbar.
- When a script editor is open on a small screen, the script list will be hidden and the editor will have `position: static` to avoid scroll glitches. In the meantime, the height of the editor is set to `100vh + 1px` which is a bit larger than the screen height to trigger a body scroll event.
> fix: let body overflow to hide toolbar in Firefox Android

- src/background/index.js
- src/popup/style.css
- src/popup/views/app.vue
Clicking the button adds the exception and confirms the UI.
The button's title shows the text that will be used i.e. `*://domain/*`
The input now shows just the new entry, not all excludes of the script as before, because it's too small. The users can open the editor to edit the entire list conveniently (this isn't mentioned anywhere in the UI though).
Type | image
-|-
Short | ![pic](https://user-images.githubusercontent.com/1310400/218315612-8d57e7ab-95f9-4615-8367-6ae2fe0f0872.png)
Medium | ![image](https://user-images.githubusercontent.com/1310400/218316410-43ba0209-8828-49db-bd5e-52d664ad8dca.png)
Super-long + info expanded | ![image](https://user-images.githubusercontent.com/1310400/218316497-2fac1392-c8a7-4c9a-ab78-87d41faeb57e.png)
> feat: simplified excluding of domain in popup

- src/common/safe-globals.js
I'm sorry but it is possible to have characters "16" in the randomly generated UUID of the extension:
And the real question is: why `split()`?
> fix: wrong way to remove suffix from icon URL

- .browserslistrc
- src/background/index.js
- src/common/ui/index.js
- src/manifest.yml
Increasing `strict_min_version` to 57, the first multi-process Firefox Quantum.
Currently it's 52 but Firefox 52 doesn't properly support many of the `browser` API we use in Violentmonkey anyway, i.e. the extension is half-broken. The reason people still use it is probably because 52 is the last version that can run in Windows XP. However it's so terribly slow compared to the modern Firefox (at least WebExtensions API) that they are really shooting themselves in the leg by still using it.
Here's the AMO statistics for the outdated FF:
version|daily update checks
-|-
Firefox 52 | ~80
Firefox 56 | ~40
Firefox 68 | ~5
Firefox 72 | ~25
Firefox 78 | ~40
Firefox 92 | ~40
Firefox 93 | ~40
Firefox 94 | ~50
Firefox 95 | ~70
---
This will get rid of ~30 manifest warnings in the AMO dashboard …
> fix: require Firefox 57+

- src/_locales/es/messages.yml
- src/_locales/es_419/messages.yml
- src/_locales/fr/messages.yml
- src/_locales/it/messages.yml
- src/_locales/ja/messages.yml
- src/_locales/ko/messages.yml
- src/_locales/pt_BR/messages.yml
- src/_locales/pt_PT/messages.yml
- src/_locales/ro/messages.yml
- src/_locales/ru/messages.yml
- src/_locales/tr/messages.yml
- src/_locales/vi/messages.yml
- src/_locales/zh_CN/messages.yml
- src/_locales/zh_TW/messages.yml
Weirdly most languages retained the same translation with the word "Default" in #1774 even though they all should have been cleared when I updated the original labelInjectionMode. Either most translators have reused the old message by mistake or it's a bug in transifex.
> chore: strip "default" from labelInjectionMode

- scripts/amo-upload.mjs
- scripts/version-helper.js
Fixes AMO warning:
> The version string should be simplified because it won't be compatible with Manifest Version 3 and above. The version should be a string with 1 to 4 numbers separated with dots. Each number should have up to 9 digits and leading zeros will no longer be allowed. Letters will no longer be allowed either.
Not sure I did it correctly, please review, @gera2ld.
> chore: use numeric version for AMO beta

- src/background/utils/storage-fetch.js
- src/background/utils/update.js
- src/common/limit-concurrency.js
Limits doCheckUpdate to 2 in parallel + 250ms pause in-between.
Limits resource requests to 4 in parallel.
> feat: check max 2 scripts at once in updateAll

- src/_locales/en/messages.yml
Before I learned from experience how the checkbox worked, I interpreted the label as if ticking the checkbox and then closing the tab would make Violentmonkey track the file.
> fix: clarify 'Track local file' checkbox label

- package.json
- src/background/index.js
- src/background/utils/tester.js
- src/common/tld.js
- test/mock/polyfill.js
- yarn.lock
The PR replaces `tldjs` with `tldts`.
`tldjs` is no longer actively maintained. The latest commit of the `tldjs` repository occurred 5 years ago and the prior npm publish of the `tldjs` package was 6 years ago, while the `tldts` remains actively maintained.
Also, `tldts` is about 2x faster than `tldjs`, see benchmark suite: https://replit.com/@isukkaw/tldjs-vs-tldts
> refactor: replace `tldjs` w/ `tldts`

- src/background/utils/notifications.js
- src/background/utils/preinject.js
* auto-remove notification once its initiator context is dead
* to prevent removal, the userscript can specify `zombieTimeout` (number of milliseconds) in `GM_notification` - I wonder if we should limit it to 24hours maybe just in case?
> feat: add zombieTimeout to GM_notification

- src/_locales/en/messages.yml
- src/common/ui/code.vue
- src/common/ui/style/style.css
- src/options/index.js
- src/options/style.css
- src/options/views/edit/index.vue
- src/options/views/edit/settings-update.vue
- src/options/views/edit/settings.vue
- src/options/views/edit/values.vue
- src/types.d.ts
Fixes #1901.
Stage | pic
-|-
Editor right after opening is gray, there's a red hint, and no buttons to save | ![image](https://github.com/violentmonkey/violentmonkey/assets/1310400/46073f46-41d4-4a61-bc13-1e339b237f1f)
Editor after trying to type or clicking the red label (it's clickable only for non-removed scripts) | ![image](https://github.com/violentmonkey/violentmonkey/assets/1310400/e016d394-01ef-4e12-a43f-7f0e1499ceb7)
When enabled the option becomes red and the note stays on screen until the script is saved | ![image](https://github.com/violentmonkey/violentmonkey/assets/1310400/7e615ef3-31f2-417d-965c-f4ff657774e8)
The option in the settings tab is also red when enabled | ![image](https://github.com/violentmonkey/violentmonkey/assets/1310400/8034ff6a-487f-4c4a-aa5b-0e9fb6aa06f1) …
> feat: show option to allow edits in updated scripts

- src/options/views/edit/index.vue
- src/options/views/edit/settings.vue
I've used an existing translatable string `Enable`:
fixes #1953
> feat: add `Enable` option in editor settings

- src/_locales/en/messages.yml
- src/background/utils/options.js
- src/common/options.js
- src/options/utils/index.js
- src/options/views/tab-installed.vue
- src/options/views/tab-settings/index.vue
- src/options/views/tab-settings/vm-import.vue
- src/options/views/tab-settings/vm-maintenance.vue
* fixes #1995: add `Reset settings` and `Remove all scripts` buttons in VM settings page.
* Both show a confirmation first
* Resetting, like vacuuming, shows the number of changes in the button's text + json values in the tooltip
* Removing uses Recycle bin to make it harder to shoot oneself in the leg by accident
* show `Undo` as a button next to `Import` button after importing instead of a post-import confirmation, which was both redundant and inconvenient as closing it would lose the button so the users had to open a new tab for Violentmonkey dashboard or settings if they wanted to test something and possibly undo it.
@gera2ld, WDYT? Also, editing+saving a locale doesn't run `copyI18n` in gulpfile anymore (even though it has gulp.watch for the paths) while running `gulp dev`, probably …
> feat: add "Reset settings" and "Remove all scripts"

- src/background/utils/db.js
Fixes #2037.
I wonder if we should show both dates in the tooltip in the dashboard and add a sorting mode for lastModified? It might be convenient to find the recently customized scripts.
OTOH, this might be rare.
> fix: set lastUpdated only if code changed

- src/options/style.css
- src/options/views/edit/index.vue
- src/options/views/tab-installed.vue
Fix #2088
The current implementation is broken on a large screen because `.editor-open .page-options` is only hidden on a small screen while `position: static` is always set for a touch screen.
I try to use the same behavior for both desktop and mobile in this PR for easier debugging.
> Fix editor style by using largest possible viewport

- src/popup/views/app.vue
Now this should work with all types of zoom:
1. OS zoom
2. Browser settings -> page zoom
3. Ctrl-wheel zoom in Violentmonkey dashboard (either below or above 100%) then open the popup for a web tab
@gera2ld, please test it on a real mobile, I only tested in the emulator. It should fit the entire height of the device as it did previously, I just want to confirm.
> fix: improve auto-size in popup

- gulpfile.js
- src/manifest.yml
This pull request adds HiDPI/Retina icon support for high resolution displays. The difference should be visible in the screenshots below.
before (no HiDPI support) | after (HiDPI support)
--- | ---
> feat: HiDPI/Retina icons

- gulpfile.js
- src/manifest.yml
It's me again, the 64px icon has to be built so it can show up in the panel (see #2240, <https://github.com/violentmonkey/violentmonkey/commit/82895bfb5895763dc7e17e4f2aaebace9bad125e>).
> fix: add 64px icon to `gulpfile.js` and `manifest.yml`

- src/background/sync/base.js
Many servers do not set a `Cache-Control` header, and since Violentmonkey also does not set `Cache-Control` on requests, the browser will fallback to ["Heuristic caching"](https://www.mnot.net/blog/2017/03/16/browser-caching#heuristic-freshness).
In some cases this can result in data loss: A user could create a script in "Browser X", and run sync. "Browser Y" could then start it's sync, but the [request for the metadata file](https://github.com/violentmonkey/violentmonkey/blob/f7e10dbbaf3cfe846a06508acf64b3bd5a70aa09/src/background/sync/base.js#L313-L321) ( `/Violentmonkey/Violentmonkey`) might be served from the browser's cache. In such a case, "Browser Y" Violentmonkey would remove the newly added script from cloud storage as it didn't see the script in the metadata file.
Unfortunately, …
> Ignore browser cache during sync as it can cause data loss
