- src/_locales/cs/messages.json
Violentmonkey was completely translated into Czech, also several changes in previous translation was made.
> Updated Czech translation

- src/_locales/ru/messages.json
Now Russian localization is complete :)
> Update Russian localization

- src/_locales/ro/messages.yml
> Translated messages.yml to Romanian

- src/_locales/vi/messages.yml
> add Vietnamese translate

- src/_locales/es/messages.yml
> Updated spanish translation

- src/_locales/hr/messages.yml
adds Croatian [Hrvatski] translation
> messages [Croatian]

- src/_locales/pl/messages.yml
> Update Polish translation

- src/_locales/de/messages.yml
This time in a single commit - I hope it meets your standards. 😄
> Update for German locales

- src/_locales/de/messages.yml
A couple of small tweaks, after seeing my translation in action the first time.
> Update for German locale

- src/_locales/ru/messages.yml
Added missing strings and updated existing ones.
> Update RU locale

- src/injected/utils.js
This fixes #173. And makes Violentmonkey work on recent builds of Firefox 58 on pages with CSP.
> Change injection technique to use src with Blob

- src/_locales/pt_BR/messages.yml
Used pt_PT as a base, changed some words.
> Add Portuguese Brazilian translation

- src/_locales/el/messages.yml
Hi, I completed part of the Greek translation. I currently don't have enough free time to complete the rest, but I believe I'll have it ready by the end of February.
> Greek locales

- src/_locales/it/messages.yml
> Fixed typo.

- src/_locales/pt_BR/messages.yml
Based on PT-EU locale, with some changes.
> Update for Portuguese Brazilian locale

- src/_locales/it/messages.yml
Many messages were missing, some were incorrect or unclear.
> Updates and fixes for Italian locale

- src/_locales/cs/messages.yml
- src/_locales/de/messages.yml
- src/_locales/el/messages.yml
- src/_locales/en/messages.yml
- src/_locales/es/messages.yml
- src/_locales/fi/messages.yml
- src/_locales/fr/messages.yml
- src/_locales/hr/messages.yml
- src/_locales/id/messages.yml
- src/_locales/it/messages.yml
- src/_locales/ja/messages.yml
- src/_locales/ko/messages.yml
- src/_locales/pl/messages.yml
- src/_locales/pt_BR/messages.yml
- src/_locales/pt_PT/messages.yml
- src/_locales/ro/messages.yml
- src/_locales/ru/messages.yml
- src/_locales/sk/messages.yml
- src/_locales/sr/messages.yml
- src/_locales/tr/messages.yml
- src/_locales/uk/messages.yml
- src/_locales/vi/messages.yml
- src/_locales/zh_CN/messages.yml
- src/_locales/zh_TW/messages.yml
- src/common/ui/style/style.css
- src/options/views/tab-about.vue
- src/options/views/tab-installed.vue
- src/options/views/tab-settings/index.vue
- src/popup/style.css
- src/popup/views/app.vue
I fixed a lot of mistakes or missing strings.
Some (two) strings were not translatable so I fixed that.
I couldn’t find a way to make the popup size adaptable, so I increased its size a bit, see before/after:
> Update French translation

- src/background/utils/update.js
> Remove <span> tags from the message

- src/_locales/ru/messages.yml
> Russian language

- src/background/utils/requests.js
> Add support for modifying Sec- headers

- src/background/utils/script.js
- src/injected/web/index.js
- test/background/script.test.js
Fixes #610.
I wonder if I should write some tests for the parser?  
If so, I'll probably need some help as I don't see an existing analog.
> allow extra/missing spaces in meta: around // and start/end/keys

- .browserslistrc
- .eslintrc.js
- gulpfile.js
- package.json
- scripts/plaid.conf.js
- src/background/utils/options.js
- src/common/index.js
- src/common/options.js
- src/common/polyfills.js
- src/common/ui/setting-check.vue
- src/common/util.js
- src/common/zip.js
- src/confirm/index.js
- src/injected/content/index.js
- src/injected/content/util.js
- src/injected/web/index.js
- src/manifest.yml
- src/options/index.js
- src/options/views/feature.vue
- src/options/views/tab-installed.vue
- src/options/views/tab-settings/index.vue
- src/options/views/tab-settings/vm-export.vue
- src/options/views/tab-settings/vm-import.vue
- src/popup/index.js
- src/popup/style.css
- yarn.lock
browserslist:
```
Chrome >= 55
Firefox >= 52
```
close #622
> Drop support for older browsers

- src/background/index.js
- src/background/utils/commands.js
- src/common/browser.js
- src/manifest.yml
> feat: add in-browser/global hotkeys for popup and dashboard

- scripts/plaid.conf.js
Fixes a rare FOUC reintroduced by #649.
> fix: prevent occasional FOUC

- src/background/sync/base.js
- src/background/sync/googledrive.js
> fix: set initial remoteMetaData to an object

- package.json
- src/background/utils/requests.js
- src/common/util.js
- src/injected/web/gm-api.js
- yarn.lock
Attaches onBeforeSendHeaders listener only when a GM_xhr is active, automatically detaches when all done.
> refactor VM- headers handling, use webRequest only when needed

- src/background/utils/update.js
- src/common/index.js
> No cache on update

- src/injected/web/gm-api.js
> fix: prevent infinite loop in gm4-polyfill.js for GM.addStyle

- src/injected/web/gm-api.js
> fix: do not modify console.log

- src/_locales/es/messages.yml
- Fixed some messages.
- Added some missing messages.
> Spanish translation update

- src/injected/web/requests.js
> feat: support GM/TM 'binary' option in GM_xmlhttpRequest

- src/injected/web/gm-wrapper.js
Fix `window.close` in `content` mode in Firefox.
Previously `this.window` returns the real `window` instead of the wrapper due to an improper check. As a result, `@grant window.close` does not work.
> fix window.close in Firefox

- src/background/utils/requests.js
> feat: show all headers in GM_xhr response

- src/background/utils/db.js
> fix: recognize GM.* grants in scriptsWithValue

- src/injected/web/gm-api.js
- src/injected/web/load-scripts.js
> feat: polyfill cloneInto, exportFunction, createObjectIn

- src/injected/content/index.js
- src/injected/content/inject.js
- src/injected/utils/helpers.js
- src/injected/web/requests.js
> fix: use XML-compatible createElementNS

- src/injected/content/inject.js
Displays special chars as unicode fullwidth `＃／：？` in the `//# sourceURL` comment.
> fix: show #/:? in .user.js names as fullwidth chars

- src/background/utils/tester.js
> fix: /regexp/ rules in autoReg

- src/_locales/cs/messages.yml
- src/_locales/de/messages.yml
- src/_locales/el/messages.yml
- src/_locales/en/messages.yml
- src/_locales/es/messages.yml
- src/_locales/fi/messages.yml
- src/_locales/fr/messages.yml
- src/_locales/hr/messages.yml
- src/_locales/id/messages.yml
- src/_locales/it/messages.yml
- src/_locales/ja/messages.yml
- src/_locales/ko/messages.yml
- src/_locales/pl/messages.yml
- src/_locales/pt_BR/messages.yml
- src/_locales/pt_PT/messages.yml
- src/_locales/ro/messages.yml
- src/_locales/ru/messages.yml
- src/_locales/sk/messages.yml
- src/_locales/sr/messages.yml
- src/_locales/tr/messages.yml
- src/_locales/uk/messages.yml
- src/_locales/vi/messages.yml
- src/_locales/zh_CN/messages.yml
- src/_locales/zh_TW/messages.yml
- src/background/index.js
- src/common/options-defaults.js
- src/options/views/tab-settings/index.vue
> Custom update interval

- src/_locales/en/messages.yml
- src/options/views/edit/help.vue
- src/options/views/edit/index.vue
* feat: add documentation link in editor help tab, fixes #493
* ui: make nav items more visible
* fix: hide Values tab in editor for new scripts
> Editor help and fixes

- src/background/utils/requests.js
#743 had a type bug, T_T maybe we should switch to TypeScript one day...
> fix: headers is an object, not an array

- src/background/utils/requests.js
> fix: first-party cookie isolation in FF

- src/background/utils/tester.js
- src/popup/style.css
- src/popup/views/app.vue
The idea was mentioned in #726.
> feat: show original rule text in blacklist reason in popup

- src/background/utils/tabs.js
- src/common/ua.js
> fix: don't rely on navigator.userAgent

- src/common/ui/code.vue
https://github.com/violentmonkey/violentmonkey/issues/488#issuecomment-568923996
> fix: highlight the search input when nothing is found

- src/common/ui/code.vue
- src/common/ui/style/style.css
> feat: autosize editor search input fields

- src/background/utils/requests.js
Fixes #771.
Had to rename `requestHeaders` to `headers` to keep the added code on one line.
> fix: don't send cookies twice in FF

- src/common/ui/code.vue
> Fix search copy

- src/_locales/en/messages.yml
- src/background/index.js
- src/background/utils/db.js
- src/options/views/tab-installed.vue
> feat: show "empty now!" in Recycle Bin + number of removed scripts

- src/injected/content/index.js
- src/injected/content/inject.js
- src/injected/utils/index.js
- src/injected/web/index.js
Implemented per https://bugzil.la/1294935 and https://stackoverflow.com/a/46081249
Tested on https://pcrypt.org/
> feat: use the faster cloneInto instead of JSON.stringify

- src/injected/content/requests.js
- src/injected/utils/helpers.js
- src/injected/web/requests.js
Fixes a bug added in #778.
Observed on GitHub.
> fix: fetching of blob URLs may be blocked by page CSP

- src/background/utils/requests.js
- src/injected/web/requests.js
> fix: ignore Set-Cookie response header for anonymous gmxhr

- src/background/utils/values.js
Looks like I didn't double-check my 35a3fa9... but at least I got it right before a release!
> fix: map is an object

- src/options/utils/hotkeys.js
> fix: don't intercept hotkeys in unrelated inputs

- src/options/views/tab-settings/vm-export.vue
> fix: set content-type for exported blob

- src/background/sync/googledrive.js
- src/background/utils/search.js
> fix: GoogleDrive auth in Edge

- src/_locales/en/messages.yml
- src/common/ui/style/style.css
- src/options/views/edit/settings.vue
> fix: rearrange and simplify notify update option

- src/common/ui/code.vue
> fix: CodeMirror selection color in contentediable mode

- src/background/sync/base.js
- src/background/sync/webdav.js
- src/common/ui/style/style.css
- src/options/views/tab-settings/vm-sync.vue
Fixes #823: `http://` and `/` will be added to WebDAV URLs as needed.
> Fix webdav

- package.json
- src/_locales/cs/messages.yml
- src/_locales/de/messages.yml
- src/_locales/el/messages.yml
- src/_locales/en/messages.yml
- src/_locales/es_419/messages.yml
- src/_locales/fi/messages.yml
- src/_locales/fr_FR/messages.yml
- src/_locales/hr/messages.yml
- src/_locales/id/messages.yml
- src/_locales/it_IT/messages.yml
- src/_locales/ja/messages.yml
- src/_locales/ko/messages.yml
- src/_locales/pl/messages.yml
- src/_locales/pt_BR/messages.yml
- src/_locales/pt_PT/messages.yml
- src/_locales/ro/messages.yml
- src/_locales/ru/messages.yml
- src/_locales/sk_SK/messages.yml
- src/_locales/sr/messages.yml
- src/_locales/tr/messages.yml
- src/_locales/uk/messages.yml
- src/_locales/vi/messages.yml
- src/_locales/zh_CN/messages.yml
- src/_locales/zh_TW/messages.yml
- src/common/ui/style/style.css
- src/options/views/tab-about.vue
- src/options/views/tab-installed.vue
- yarn.lock
- Add a link to contributors list instead of personal email
> Update tooltip style in dark mode

- src/background/utils/requests.js
- src/common/util.js
- src/injected/content/requests.js
- src/injected/web/requests.js
Fixes #843.
The problem was that Chrome doesn't allow extensions to access their own chrome-extension:// URLs in incognito, I forgot about that initially so now this PR sends the blob/buffer as separate messages in 64MB string chunks.
> Fix incognito blob

- src/common/browser.js
- src/injected/web/load-scripts.js
> fix: prevent interception of thisObj

- src/background/utils/tester.js
- src/common/cache.js
Makes getScriptsByURL faster by up to ~25%, hence also benefiting preinject. Noticeable when rebuilding all rules which happens when the cache is expired: ~48ms -> ~35ms.
It also removes the potentially memory-hungry caching of per-URL-per-regexp results: there's no need for that because V8 superbly optimizes a hot execution path (~20ms in the second run, ~5ms in the 3rd or 4th runs).
> refactor: speedup URL tester

- src/background/index.js
- src/background/utils/db.js
- src/background/utils/icon.js
- src/background/utils/preinject.js
- src/common/browser.js
- src/common/index.js
- src/injected/content/bridge.js
- src/injected/content/index.js
- src/injected/content/inject.js
- src/injected/web/requests.js
- src/popup/index.js
* fix: update icon on all tabs when isApplied is changed
* fix: support `onloadstart` in gmxhr
* refactor: reuse wrappers for messaging from browser.js
* refactor: move some logic from tabs to bg
* analyze @noframes
* call SetBadge directly
* call SetPopup only if popup is shown in that tab
> Tweaks & fixes

- src/injected/web/gm-wrapper.js
> fix: patch toString on proxy in Firefox

- src/background/plugin/index.js
Fixes #870.
Didn't test it though.
@gera2ld, this particular PR is worth releasing a new version ASAP, I think.
> fix: plugin.list() does not return a Promise

- src/injected/utils/helpers.js
- src/injected/web/requests.js
> fix: keep original Blob

- src/background/utils/icon.js
In Stylus extension we discovered this error cannot be *prevented* reliably regardless of whether we checked for the tab state or not. It can be suppress though since Chrome 67+ which added callbacks to all browserAction methods.
> fix: suppress the occasional no-tab-id error in Chrome 67+

- src/injected/content/requests.js
> fix: don't reset allChunks if it's already true

- src/background/utils/tabs.js
> fix: TabOpen in incognito windows

- src/background/utils/requests.js
- src/injected/content/requests.js
- src/injected/web/requests.js
Turns out buffer2string is unbelievably slow with large payloads: it takes several seconds to encode/transfer/decode ~60MB video on a 4GHz i7 CPU, which is just ridiculous.
* Blobs are back for non-incognito tabs, and they're essentially *instantaneous*
* blob/buffer is sent into the page realm directly as DOM messaging uses structured cloning
* `responseText` will be sent just once (like `response`) and remembered in web/*
* `responseText` that's equal to `response` will be deduplicated internally in the message
* `responseHeaders` will be sent only when changed
* removed try/catch in background's httpRequest because handleCommandMessage catches all exceptions anyway and reports to the caller
> speedup: gmxhr with very large responses

- src/injected/web/gm-wrapper.js
Fixed a few bugs:
- `window` is supposed to be the wrapper when there are `@grant`s, but it's `unsafeWindow` now.
```js
> console.log(this, window, unsafeWindow)
< Proxy {...}  Window {...}  Window {...}
// But the expected result is
< Proxy {...}  Proxy {...}  Window {...}
```
- The wrapper is a Proxy with a target object of `local`. When calling `Object.keys(wrapper)`, a `TypeError` is thrown:
```js
> console.log(Object.keys(wrapper));
< Uncaught TypeError: 'getOwnPropertyDescriptor' on proxy: trap returned descriptor for property 'top' that is incompatible with the existing property in the proxy target
at Function.keys (<anonymous>)
```
This is caused by violation of [invariants](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/getOwnPropert …
> Fix window and globals

- src/injected/web/gm-wrapper.js
> fix: don't expose window.has

- src/options/views/edit/index.vue
- src/options/views/edit/values.vue
> fix the values editor

- src/injected/web/index.js
https://github.com/violentmonkey/vm-detector/issues/1
> Add vm-detector support for sleazyfork.org

- src/_locales/cs/messages.yml
- src/_locales/de/messages.yml
- src/_locales/el/messages.yml
- src/_locales/en/messages.yml
- src/_locales/es_419/messages.yml
- src/_locales/fi/messages.yml
- src/_locales/fr/messages.yml
- src/_locales/hr/messages.yml
- src/_locales/id/messages.yml
- src/_locales/it/messages.yml
- src/_locales/ja/messages.yml
- src/_locales/ko/messages.yml
- src/_locales/pl/messages.yml
- src/_locales/pt_BR/messages.yml
- src/_locales/pt_PT/messages.yml
- src/_locales/ro/messages.yml
- src/_locales/ru/messages.yml
- src/_locales/sk/messages.yml
- src/_locales/sr/messages.yml
- src/_locales/tr/messages.yml
- src/_locales/uk/messages.yml
- src/_locales/vi/messages.yml
- src/_locales/zh_CN/messages.yml
- src/_locales/zh_TW/messages.yml
- src/common/ui/style/style.css
- src/confirm/views/app.vue
- src/options/style.css
- src/options/views/tab-about.vue
- src/options/views/tab-settings/index.vue
> add privacy policy in About tab

- src/background/utils/requests.js
Fixes #980.
* In Chrome 74+ the listener can't be attached during page load https://crbug.com/1074282
* `tabId: -1` did nothing as it turns out the API ignores this value and there's no way to limit tabId to the background script
> fix: Chrome bug workaround for gmxhr

- src/options/views/edit/help.vue
- src/options/views/edit/index.vue
The change seems trivial but since it involves Vue (which is not my forte) I'm requesting a review just in case.
> feat: use 'save' hotkey in all editor panels

- src/injected/web/gm-wrapper.js
Technically this is the same as old code but now it works in stages: 1) copies **all** metadata keys while renaming match/include/exclude, 2) ensures `''` for five known props.
Fixes #1031.
> feat: expose all metadata keys in GM_info.script

- src/_locales/ko/messages.yml
I added some missing translations.
>  Update Korean translation

- package.json
- yarn.lock
> chore: update CodeMirror 5.58.0

- src/background/utils/requests.js
Fixes #1066 (the bug with the length of response reported in comments).
The problem was that while XHR is still loading, response and responseText contain only partial info per the specification, for example 65536 bytes.
The fix seems to be working correctly ~at first try but I want to test it more because I haven't yet analyzed the content script (it may need some changes as well)~.
> fix: gmxhr with partial responses while still loading

- src/injected/web/gm-wrapper.js
> fix: also bind setter for unforgeable globals

- src/injected/content/inject.js
Fixes #1104 as much as possible.
With `@inject-into content` our own wrapper code won't even run so there'll be no error message at all. There's nothing we can do about it, the error doesn't seem to be reported anywhere so this is a Firefox bug I guess.
In normal mode the error source is incorrectly attributed by Firefox to the page itself. This can be intercepted. This PR explicitly prints such unrecoverable errors that occur during appendChild() call.
P.S. In Chrome the same happens when devtools was closed at the time the error was printed, but when devtools is opened the error is printed with correct attribution. However, there's nothing we can do about it because the error cannot be intercepted via `error` event or try-catch and anyway the user may just reload the page with devtools …
> feat: show script name in syntax errors during injection

- src/_locales/en/messages.yml
- src/common/hook-setting.js
- src/common/ui/setting-text.vue
- src/options/views/tab-settings/vm-blacklist.vue
- src/options/views/tab-settings/vm-css.vue
- src/options/views/tab-settings/vm-editor.vue
- src/options/views/tab-settings/vm-template.vue
> fix: toggle save/reset buttons depending on value

- src/common/ui/setting-text.vue
- make code a little more declarative
- change saving behavior a bit to make it more intuitive: reload page before clicking *Save* should discard unsaved changes
> fix: auto save only if there is no save button

- src/common/load-script-icon.js
- src/options/views/script-item.vue
> show SVG icons again

- src/background/utils/requests.js
Fixes #1140 part 1 (detection), part 2 is already fixed in 2.12.9.
> fix: detect GH-releases + update .user.js detector

- src/confirm/views/app.vue
- src/injected/index.js
> fix: auto-close .user.js tab when installer closes

- src/options/views/script-item.vue
Typical screen sizes:
* 1366x768: 2 columns
* 1920x1080: 3 columns
* 2560x1440: 4 columns
> feat: multiple columns in dashboard on wide screens

- src/background/index.js
- src/background/utils/db.js
- src/background/utils/preinject.js
Now it checks everything (hopefully) that affects the preinject cache: autoupdates, requires, resources, values.
> fix: clear preinject cache for more db changes

- src/background/utils/notifications.js
- src/background/utils/tabs.js
- src/background/utils/update.js
- src/popup/views/app.vue
> feat: open editor on clicking update notification

- src/injected/content/index.js
Fixes #1182.
Avoids flicker when renaming GM menu items by postponing the first SetPopup notification to the next event cycle so scripts can rename their menus in the same event loop cycle:
Demo:
```js
// ==UserScript==
// @name        GM_registerMenuCommand 
// @namespace   Violentmonkey Scripts
// @match       https://www.example.com/
// @grant       GM_registerMenuCommand
// @grant       GM_unregisterMenuCommand
// ==/UserScript==
let i = 0;
GM_registerMenuCommand(`test ${i || ''}`, console.log);
setInterval(() => {
GM_unregisterMenuCommand(`test ${i || ''}`);
GM_registerMenuCommand(`test ${++i}`, console.log);
}, 1000);
```
> feat: avoid flicker when renaming GM menu items

- src/_locales/en/messages.yml
- src/background/utils/db.js
- src/common/ui/index.js
- src/options/views/edit/settings.vue
- src/popup/index.js
- src/popup/style.css
- src/popup/utils/index.js
- src/popup/views/app.vue
Fixes #367.
<details><summary>Initial implementation, now rejected, see comments below</summary>
Menu | UI
-|-
</details>
> feat: add "exclude" to popup menu

- src/common/ui/message.vue
- src/common/ui/setting-check.vue
- src/common/ui/style/style.css
- src/confirm/views/app.vue
- src/options/style.css
- src/options/views/edit/help.vue
- src/options/views/edit/index.vue
- src/options/views/edit/values.vue
- src/options/views/script-item.vue
- src/options/views/tab-about.vue
- src/options/views/tab-installed.vue
- src/options/views/tab-settings/index.vue
- src/options/views/tab-settings/vm-export.vue
- src/options/views/tab-settings/vm-import.vue
- src/options/views/tab-settings/vm-sync.vue
* deduplicate `<setting-check>` by adding `label` prop and `slot`
* deduplicate classes like `ml-1` on children to a single class like `ml-1c` on parent
* ~deduplicate `flex flex-col` and `flex flex-wrap` to simply `flex-col` and `flex-wrap` by including `display:flex` in each one~
> deduplicate css

- src/background/utils/db.js
- src/background/utils/storage-fetch.js
- src/common/storage.js
- src/common/ui/code.vue
- src/confirm/views/app.vue
- src/injected/web/gm-api.js
- src/options/views/edit/externals.vue
- src/options/views/edit/index.vue
Fixes #869.
In addition to the feature itself I fixed a few bugs discovered while making this PR.
>  feat: show @require and @resource in editor

- src/background/utils/notifications.js
- src/background/utils/update.js
> fix: group multiple update notifications in one

- src/background/utils/requests.js
When tab closed or page reloaded, the xhr won't stop. This could be waste of time and bandwidth when requesting large data.
> fix: abort GM_xmlhttpRequest on page redirect

- src/common/ui/style/style.css
- src/options/views/tab-settings/vm-sync.vue
Only disable the username and password fields.
> Don’t disable Server URL for anonymous logins

- src/common/ui/style/style.css
- src/options/views/tab-installed.vue
> fix: ensure config UI is visible in compact dashboard

- gulpfile.js
- scripts/plaid.conf.js
- src/common/zip.js
since Firefox blocks inline workers.
fix #1253
> fix: use z-worker.js instead of inline worker

- src/background/index.js
- src/background/utils/requests.js
> fix: clear previous requests when GetInjected is fired

- src/options/views/tab-settings/vm-import.vue
> fix: add missing support for "readScriptOptions"

- src/popup/views/app.vue
...to make them more consistent and friendly to keyboard navigation
> fix: show tooltips in the bottom for popup buttons

- src/options/views/edit/values.vue
> fix: preserve current unsaved value in storage editor

- src/_locales/en/messages.yml
- src/background/utils/db.js
- src/common/index.js
- src/confirm/views/app.vue
- src/injected/content/index.js
- src/injected/web/index.js
Fixes #1259.
* ### Reinstalling (same code)
* ### Installing
> feat: indicate in confirm UI when reinstalling

- src/options/views/edit/index.vue
Depends on https://github.com/violentmonkey/vm-shortcut/pull/4
> fix: use K_SAVE hotkey + enable it in non-code tabs

- src/common/ui/code.vue
> fix: finding in folded code

- src/injected/content/index.js
- src/injected/content/inject.js
- src/injected/utils/helpers.js
- src/injected/web/gm-api.js
https://www.tampermonkey.net/documentation.php#GM_addElement
Fixes #1335.
> feat: implement GM_addElement + GM.addElement

- src/confirm/views/app.vue
* feat: add Ctrl/Cmd-Enter hotkey to confirm installation
* feat: show home/support urls fully
> feat: hotkey to confirm install + show home/support urls

- src/_locales/en/messages.yml
- src/common/options-defaults.js
- src/common/ui/code.vue
- src/common/ui/style/index.js
- src/common/ui/style/style.css
- src/options/views/tab-settings/vm-editor.vue
- src/options/views/tab-settings/vm-sync.vue
Fixes #737, #924.
@gera2ld, can I upload to transifex all locales if I manually edit `descEditorOptions` in each one via `tx push -t`?
> feat: CodeMirror theme option

- src/_locales/en/messages.yml
- src/common/date.js
- src/common/options-defaults.js
- src/common/ui/setting-text.vue
- src/options/views/tab-settings/vm-export.vue
Fixes #1378 using a subset of [moment.js tokens](https://momentjs.com/docs/#/displaying/format/).
The tooltip:
@gera2ld, @AlttiRi, PTAL.
> feat: customize export file name

- src/injected/content/util-content.js
- src/injected/web/gm-api.js
- test/injected/gm-resource.test.js
```js
GM_getResourceURL(name) // blob: URL
GM_getResourceURL(name, true) // blob: URL
GM_getResourceURL(name, false) // data: URL
```
> feat: add `isBlobUrl` parameter to GM_getResourceURL

- src/background/sync/base.js
as tabId will be -1 for initial requests intercepted by service worker in Chromium-based browsers.
Fix sync authorization when service worker has been installed for violentmonkey.github.io
> fix: do not filter tabId for onBeforeRequest

- src/background/utils/preinject.js
- src/background/utils/script.js
- src/injected/content/cmd-run.js
- src/injected/content/index.js
- src/injected/content/inject.js
- src/injected/web/gm-api-wrapper.js
- src/injected/web/index.js
- test/background/script.test.js
Fixes #966.
Fixes https://github.com/violentmonkey/violentmonkey/discussions/1442.
* `@grant` is ignored, `GM` and `GM_*` aren't available.
* I will add documentation when/if this is merged.
> feat: `@unwrap` meta key

- src/injected/web/safe-globals-web.js
https://github.com/violentmonkey/violentmonkey/issues/1432
> make SafePromise.prototype.then unreplaceable

- src/injected/content/bridge.js
- src/injected/content/requests.js
> fix: ensure messages are ordered

- .github/workflows/ci.yml
- .github/workflows/release.yml
> fix: use sync secrets in actions

- src/common/ui/code.vue
> feat: show trailing spaces and trim on save

- src/background/utils/requests.js
> fix: don't let finalUrl to be undefined

- src/background/index.js
- src/background/utils/requests-api.js
- src/background/utils/requests-core.js
- src/background/utils/requests.js
- src/background/utils/tab-redirector.js
@gera2ld, requests.js seems overly "packed" to me so I've split it into 3 files. WDYT?
> refactor: split bg requests.js

- scripts/webpack.conf.js
- src/background/sync/base.js
- src/background/sync/dropbox.js
- src/background/sync/googledrive.js
- src/common/util.js
> Implement PKCE for authentication

- src/background/utils/db.js
- src/background/utils/script.js
- src/common/index.js
- src/confirm/views/app.vue
- src/injected/web/gm-api-wrapper.js
- src/options/views/edit/settings.vue
- src/options/views/script-item.vue
- src/popup/views/app.vue
These are used in more than 100 scripts on GreasyFork, and are also recognized by Tampermonkey.
> feat: read homepage from `@website` and `@source`

- src/options/utils/dragging.js
The event listener is not called.
> Fix script list reorder

- src/_locales/en/messages.yml
- src/popup/index.js
- src/popup/style.css
- src/popup/views/app.vue
> feat: show "syntax error?" in popup under names

- src/background/utils/preinject.js
> fix: script id may be 0?

- src/common/ui/index.js
- src/options/index.js
> feat: show unhandled errors in UI at the bottom

- src/_locales/en/messages.yml
- src/background/utils/preinject.js
- src/common/options-defaults.js
- src/options/views/tab-settings/index.vue
Some people may want to disable this option since it increases memory consumption.
> feat: "Alternative page mode in Firefox" option

- src/options/views/tab-installed.vue
> fix: set tab height to 100vh on large screen

- src/_locales/en/messages.yml
- src/background/utils/db.js
- src/background/utils/preinject.js
- src/common/consts.js
- src/options/views/edit/index.vue
- src/options/views/edit/settings.vue
- src/options/views/tab-settings/index.vue
> feat: customize @inject-into in script settings

- src/injected/content/gm-api-content.js
- src/injected/web/gm-api.js
- src/injected/web/gm-values.js
- src/injected/web/index.js
- src/injected/web/store.js
- src/popup/index.js
- src/popup/views/app.vue
> feat: id, title, autoClose in GM_registerMenuCommand

- src/background/utils/notifications.js
> feat: add zombieUrl to GM_notification

- src/common/ui/code.vue
- src/options/views/edit/index.vue
> fix: update tooltip alignment to avoid overflow

- src/common/ui/style/style.css
- src/options/views/tab-installed.vue
> fix: set header bar to scrollable for small screen only

- src/background/utils/db.js
- src/background/utils/values.js
- src/injected/web/gm-api-wrapper.js
- src/injected/web/gm-api.js
- src/injected/web/gm-values.js
- src/injected/web/index.js
- src/options/views/edit/values.vue
Implementation of https://github.com/Tampermonkey/tampermonkey/issues/2045.
Not yet tested to match Tampermonkey.
> feat: GM_getValues, GM_setValues, GM_deleteValues

- src/background/utils/db.js
- src/background/utils/preinject.js
- src/types.d.ts
Fix #2180 
See root cause here: https://github.com/violentmonkey/violentmonkey/issues/2180#issuecomment-2342047967
> fix: fix potential race condition for preparation

- src/common/index.js
- test/common/index.test.js
> fix: support extended language tags

- src/_locales/zh_TW/messages.yml
> Update and improve zh_TW Traditional Chinese locale
